import assert from 'node:assert/strict';
const base=process.env.COOKBRO_TEST_URL||'http://localhost:5173';
assert(['localhost','127.0.0.1'].includes(new URL(base).hostname),'Integration test must only run locally');
const signin=await fetch(base+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});const cookie=signin.headers.get('set-cookie')?.split(';')[0];assert(cookie);
const read=async()=>{const r=await fetch(base+'/api/household',{headers:{Cookie:cookie}});assert.equal(r.status,200);return r.json()};
let state=await read();
const post=async(data,extra={})=>fetch(base+'/api/household',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json',Origin:base,...extra},body:JSON.stringify({...data,revision:state.revision})});
assert.equal((await fetch(base+'/api/household')).status,401);
assert.equal((await post({action:'generate',date:'invalid',vegetarian:false})).status,400);
assert.equal((await post({action:'settings',phone1:'bad',phone2:'',allowMutton:false})).status,400);
assert.equal((await post({action:'settings',phone1:'',phone2:'',allowMutton:false},{Origin:'https://example.org'})).status,403);
const future=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+20*86400000));
let r=await post({action:'generate',date:future,vegetarian:true});assert.equal(r.status,200);state=await r.json();assert(state.plans[future].vegetarian);
r=await post({action:'takeout',date:future,meal:'dinner',enabled:true});assert.equal(r.status,200);state=await r.json();assert(state.plans[future].takeout.includes('dinner'));
r=await post({action:'confirm',date:future,confirmed:true});assert.equal(r.status,200);state=await r.json();
assert.equal((await post({action:'generate',date:future,vegetarian:false})).status,409);
assert.equal((await post({action:'takeout',date:future,meal:'dinner',enabled:false})).status,409);
const preserved=state.plans[future].preferences;
r=await post({action:'preferences',preferences:{...state.settings.preferences,servings:state.settings.preferences.servings+1}});assert.equal(r.status,200);state=await r.json();assert.deepEqual(state.plans[future].preferences,preserved);
r=await post({action:'preferences',preferences:{...state.settings.preferences,servings:preserved.servings}});assert.equal(r.status,200);state=await r.json();
assert.equal((await post({action:'swap',date:future,id:state.plans[future].lunch[2]})).status,400);
r=await post({action:'confirm',date:future,confirmed:false});assert.equal(r.status,200);state=await r.json();
const stale=await fetch(base+'/api/household',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json',Origin:base},body:JSON.stringify({action:'confirm',date:future,confirmed:true,revision:state.revision-1})});assert.equal(stale.status,409);
const restored=await read();assert.deepEqual(restored.plans[future],state.plans[future]);
console.log('PASS: authenticated persistence, anonymous rejection, origin check, input validation, confirmed-menu lock and stale-write protection. Local test plan saved 20 days ahead.');
