import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {claimDeviceLink,findSession,issueDeviceLink,readSessionToken,cookieHeader,tokenHash,sessionCookie,sessionSeconds} from '../lib/device-auth';
const sql=new DatabaseSync(':memory:');
sql.exec('CREATE TABLE device_links (token_hash TEXT PRIMARY KEY, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, redeemed_at INTEGER); CREATE TABLE device_sessions (token_hash TEXT PRIMARY KEY,label TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);');
const db={prepare(text:string){let args:unknown[]=[];const stmt=sql.prepare(text);return {bind(...values:unknown[]){args=values;return this},async first(){return stmt.get(...args as never[])||null},async run(){const result=stmt.run(...args as never[]);return {meta:{changes:Number(result.changes)}}}}},async batch(items:{run:()=>Promise<unknown>}[]){return Promise.all(items.map(x=>x.run()));}} as unknown as D1Database;
const now=Date.now();const link=await issueDeviceLink(db,now);assert.match(link.token,/^[a-f0-9]{64}$/);
assert(!JSON.stringify(sql.prepare('SELECT * FROM device_links').all()).includes(link.token),'Raw link must not be stored');
assert.equal(await findSession(db,null,now),null);assert.equal(await findSession(db,link.token,now),null);
assert.equal(await claimDeviceLink(db,'forged','Browser',now),null);
const claims=await Promise.all([claimDeviceLink(db,link.token,'First device',now),claimDeviceLink(db,link.token,'Second device',now)]);assert.equal(claims.filter(Boolean).length,1,'Exactly one concurrent redemption may succeed');
const token=claims.find(Boolean)!;assert.notEqual(token,link.token);assert(await findSession(db,token,now));
assert(!JSON.stringify(sql.prepare('SELECT * FROM device_sessions').all()).includes(token),'Raw session must not be stored');
assert.equal(await claimDeviceLink(db,link.token,'Replay',now),null);
assert.equal(await findSession(db,token,now+sessionSeconds*1000+1),null);
assert.equal(readSessionToken('other=1; '+sessionCookie+'='+token),token);
assert.equal(readSessionToken(sessionCookie+'='+token+'; '+sessionCookie+'='+token),null);
assert.equal(readSessionToken(sessionCookie+'=not-valid'),null);
assert(cookieHeader(token).includes('HttpOnly; Secure; SameSite=Strict'));assert(cookieHeader('',0).includes('Max-Age=0'));
const expired=await issueDeviceLink(db,now);assert.equal(await claimDeviceLink(db,expired.token,'Expired',expired.expiresAt),null);
await db.prepare('DELETE FROM device_sessions WHERE token_hash=?').bind(await tokenHash(token)).run();assert.equal(await findSession(db,token,now),null);
sql.close();console.log('PASS: cryptographic device links, hashed storage, atomic single-use redemption, expiration, session cookies and revocation.');
