'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Smartphone,Copy,MessageCircle,LogOut} from 'lucide-react';
import {toast} from 'sonner';
type Device={id:string;label:string;current:boolean;createdAt:number;expiresAt:number};
export default function AccountDialog({open,onOpenChange,email,provider}:{open:boolean;onOpenChange:(v:boolean)=>void;email:string;provider:string}){
 const [devices,setDevices]=useState<Device[]>([]),[link,setLink]=useState<{url:string;expiresAt:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const pairing=provider==='Private device link';
 async function load(){try{const r=await fetch('/api/auth/device');const data=await r.json() as {error?:string;devices?:Device[]};if(!r.ok)throw new Error(data.error||'Could not load devices.');setDevices(data.devices||[]);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(!open||!pairing)return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[open,pairing]);
 function handleOpenChange(next:boolean){if(!next){setLink(null);setError('');setDevices([]);}onOpenChange(next);}
 async function act(data:Record<string,string>){setBusy(true);setError('');try{const r=await fetch('/api/auth/device',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json() as {error?:string;url?:string;expiresAt?:number;ok?:boolean};if(!r.ok)throw new Error(value.error||'Could not save.');return value;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 return <Dialog open={open} onOpenChange={handleOpenChange}><DialogContent className="detail-dialog"><DialogTitle className="dialog-heading">Household access</DialogTitle><DialogDescription>Signed in with {provider}.</DialogDescription><div className="dialog-body"><p className="account-email">{email}</p><p>Invite trusted family to collaborate on this shared cookbook, menus and shopping list. Everyone invited can view and edit the household.</p>{pairing&&<><button className="button primary" disabled={busy} onClick={async()=>{const result=await act({action:'issue'});if(result?.url&&result.expiresAt)setLink({url:result.url,expiresAt:result.expiresAt});}}><Smartphone size={17}/> Invite a family member</button>{link&&<div className="device-link-box"><p><strong>Family invitation link</strong></p><p>Share this with your wife or another trusted family member. It works once, expires in 10 minutes and gives full access to this shared household.</p><div className="share-actions"><button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(link.url);toast.success('Family invitation copied.');}catch{setError('Copy is unavailable. Select the link below.');}}}><Copy size={15}/> Copy invitation link</button><a className="button" href={'https://wa.me/?text='+encodeURIComponent('Join our shared Cook Bro household. Open this private invitation within 10 minutes:\n'+link.url)} target="_blank" rel="noreferrer"><MessageCircle size={15}/> Share invitation on WhatsApp</a></div><label className="field">Invitation link<input readOnly value={link.url}/></label><p className="small-note">Expires at {new Date(link.expiresAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}. Do not forward this link beyond the person you are inviting.</p></div>}<h3 className="devices-heading">Household devices</h3><div className="device-list">{devices.map(d=><div className="device-row" key={d.id}><div><strong>{d.label}{d.current?' · This device':''}</strong><p className="small-note">Connected {new Date(d.createdAt).toLocaleDateString()}</p></div>{!d.current&&<button className="text-button" disabled={busy} onClick={async()=>{if(await act({action:'revoke',id:d.id}))void load();}}>Remove access</button>}</div>)}</div><button className="button" disabled={busy} onClick={async()=>{if(await act({action:'logout'}))window.location.replace('/sign-in');}}><LogOut size={16}/> Sign out this device</button></>}{error&&<p className="error-text" role="alert">{error}</p>}</div></DialogContent></Dialog>;
}
