'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Smartphone,Copy,MessageCircle,LogOut} from 'lucide-react';
import {toast} from 'sonner';
type Device={id:string;label:string;current:boolean;createdAt:number;expiresAt:number};
export default function AccountDialog({open,onOpenChange,email,provider}:{open:boolean;onOpenChange:(v:boolean)=>void;email:string;provider:string}){
 const [devices,setDevices]=useState<Device[]>([]),[link,setLink]=useState<{url:string;expiresAt:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const pairing=provider==='Private device link';
 async function load(){try{const r=await fetch('/api/auth/device');const data=await r.json() as {error?:string;devices?:Device[]};if(!r.ok)throw new Error(data.error||'Could not load devices.');setDevices(data.devices||[]);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(!open||!pairing)return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[open,pairing]);
 function handleOpenChange(next:boolean){if(!next){setLink(null);setError('');setDevices([]);}onOpenChange(next);}
 async function act(data:Record<string,string>){setBusy(true);setError('');try{const r=await fetch('/api/auth/device',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json() as {error?:string;url?:string;expiresAt?:number;ok?:boolean};if(!r.ok)throw new Error(value.error||'Could not save.');return value;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 return <Dialog open={open} onOpenChange={handleOpenChange}><DialogContent className="detail-dialog"><DialogTitle className="dialog-heading">Your account</DialogTitle><DialogDescription>Signed in with {provider}.</DialogDescription><div className="dialog-body"><p className="account-email">{email}</p><p>Your menus, shopping checks and preferences stay together on your connected devices.</p>{pairing&&<><button className="button primary" disabled={busy} onClick={async()=>{const result=await act({action:'issue'});if(result?.url&&result.expiresAt)setLink({url:result.url,expiresAt:result.expiresAt});}}><Smartphone size={17}/> Connect another device</button>{link&&<div className="device-link-box"><p><strong>Private sign-in link</strong></p><p>Open this on your phone, iPad or another computer within 10 minutes. It works once and grants full access to this household.</p><div className="share-actions"><button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(link.url);toast.success('Private link copied. Open it only on a device you trust.');}catch{setError('Copy is unavailable. Select the link below.');}}}><Copy size={15}/> Copy private link</button><a className="button" href={'https://wa.me/?text='+encodeURIComponent('Private Cook Bro sign-in. Open only on your own device within 10 minutes:\n'+link.url)} target="_blank" rel="noreferrer"><MessageCircle size={15}/> Share to my phone</a></div><label className="field">Device link<input readOnly value={link.url}/></label><p className="small-note">Expires at {new Date(link.expiresAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}. Keep this link private; ordinary menu sharing remains separate.</p></div>}<h3 className="devices-heading">Connected devices</h3><div className="device-list">{devices.map(d=><div className="device-row" key={d.id}><div><strong>{d.label}{d.current?' · This device':''}</strong><p className="small-note">Connected {new Date(d.createdAt).toLocaleDateString()}</p></div>{!d.current&&<button className="text-button" disabled={busy} onClick={async()=>{if(await act({action:'revoke',id:d.id}))void load();}}>Remove access</button>}</div>)}</div><button className="button" disabled={busy} onClick={async()=>{if(await act({action:'logout'}))window.location.replace('/sign-in');}}><LogOut size={16}/> Sign out this device</button></>}{error&&<p className="error-text" role="alert">{error}</p>}</div></DialogContent></Dialog>;
}
