'use client';
import {useEffect,useState} from 'react';
import {Check,Users,Utensils,Globe,Settings2} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {preferences,preferencesSchema,cuisineOptions,allergyOptions,type Preferences} from '@/lib/preferences';
import {type State} from '@/lib/food';
import {toast} from 'sonner';
function Choice({label,value,options,onChange}:{label:string;value:string;options:readonly (string|{value:string;label:string})[];onChange:(v:string)=>void}){return <label className="field">{label}<Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="profile-select"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=>{const item=typeof o==='string'?{value:o,label:o}:o;return <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>})}</SelectContent></Select></label>}
export default function HouseholdForm({state,busy,act}:{state:State|null;busy:boolean;act:(a:Record<string,unknown>)=>Promise<State|null>}){
 const [p,setP]=useState<Preferences>(preferences(state)),[ages,setAges]=useState(''),[avoid,setAvoid]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(state){const next=preferences(state);setP(next);setAges(next.childAges.join(', '));setAvoid(next.avoidIngredients.join(', '));}},[state?.settings.preferences]);
 function field<K extends keyof Preferences>(key:K,value:Preferences[K]){setP(old=>({...old,[key]:value}))}
 function number(label:string,key:'adults'|'seniors'|'servings'|'repeatDays'|'budget'|'orderMealsPerWeek',min:number,max:number){return <label className="field">{label}<input type="number" min={min} max={max} value={p[key]} onChange={e=>field(key,Number(e.target.value))}/></label>}
 function flag(label:string,key:'sharedCurry'|'includeDal'|'includeSide'){return <label className="check-label"><Checkbox checked={p[key]} onCheckedChange={v=>field(key,!!v)}/>{label}</label>}
 return <section className="profile-settings"><div className="settings-card"><Users size={24}/><h2>Who’s eating?</h2><div className="form-grid">{number('Adults, excluding seniors','adults',1,12)}{number('Older adults','seniors',0,8)}<label className="field">Children’s ages (comma separated)<input value={ages} onChange={e=>setAges(e.target.value)} placeholder="For example: 5, 12"/></label>{number('Cooking servings per meal','servings',1,24)}</div><p className="small-note">Recipes scale from a six-serving base. Adjust cooking servings to appetite and leftovers; portions are not a calorie prescription. For children under 2, get age-specific feeding advice.</p></div>
 <div className="settings-card"><Utensils size={24}/><h2>Food preferences</h2><Choice label="Diet" value={p.diet} options={[{value:'vegetarian',label:'Vegetarian (no eggs)'},{value:'eggetarian',label:'Vegetarian + eggs'},{value:'mixed',label:'Vegetarian, eggs, fish and meat'}]} onChange={v=>field('diet',v as Preferences['diet'])}/><h3>Cuisines to include</h3><div className="preference-checks">{cuisineOptions.map(c=><label key={c} className="check-label"><Checkbox checked={p.cuisines.includes(c)} onCheckedChange={v=>field('cuisines',v?[...p.cuisines,c]:p.cuisines.filter(x=>x!==c))}/>{c}</label>)}</div><h3>Exclude these allergens</h3><div className="preference-checks">{allergyOptions.map(a=><label className="check-label" key={a}><Checkbox checked={p.allergies.includes(a)} onCheckedChange={v=>field('allergies',v?[...p.allergies,a]:p.allergies.filter(x=>x!==a))}/>{a}</label>)}</div><label className="field">Other ingredients to avoid<input value={avoid} onChange={e=>setAvoid(e.target.value)} placeholder="For example: mushroom, karela"/></label><p className="small-note">Filters match listed ingredients and allergen tags. Check packaging and substitutions for hidden allergens or cross-contact. Restaurant suggestions are not allergy-filtered. All home recipes currently avoid added sugar, beef and pork.</p></div>
 <div className="settings-card"><Settings2 size={24}/><h2>Your cooking rhythm</h2><p className="small-note">Choose a main curry protein for each day. Vegetarian diets override meat and fish selections. Occasional mutton also requires enabling it below.</p><div className="weekly-proteins">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,n)=><Choice key={day} label={day+' curry'} value={p.diet==='mixed'?p.weeklyProteins[n]:'veg'} options={p.diet==='mixed'?['veg','chicken','fish','mutton']:['veg']} onChange={v=>field('weeklyProteins',p.weeklyProteins.map((item,i)=>i===n?v as Preferences['weeklyProteins'][number]:item))}/>)}</div><div className="form-grid"><Choice label="Lunch staple" value={p.lunchStaple} options={['rice','roti','paratha']} onChange={v=>field('lunchStaple',v as Preferences['lunchStaple'])}/><Choice label="Dinner staple" value={p.dinnerStaple} options={['rice','roti','paratha']} onChange={v=>field('dinnerStaple',v as Preferences['dinnerStaple'])}/>{number('Minimum days before repeating a dish','repeatDays',3,20)}<Choice label="Recipe name style" value={p.language} options={[{value:'hindi',label:'Familiar Hindi names (English letters)'},{value:'english',label:'English ingredient names'}]} onChange={v=>field('language',v as Preferences['language'])}/></div><div className="preference-checks">{flag('Cook one curry for lunch and dinner','sharedCurry')}{flag('Include dal at lunch and dinner','includeDal')}{flag('Include a lightly cooked vegetable side','includeSide')}</div><p className="small-note">Narrow cuisines, long repeat windows or many exclusions may leave no matching recipe. The app will explain the conflict instead of ignoring your choices.</p><div className="form-grid"><Choice label="Oil quantity" value={String(p.oilFactor)} options={[{value:'.5',label:'Half the recipe oil'},{value:'0.5',label:'Half the recipe oil'},{value:'0.75',label:'Three quarters'},{value:'1',label:'As written'},{value:'1.25',label:'One quarter more'}].filter(o=>o.value!=='.5')} onChange={v=>field('oilFactor',Number(v))}/><Choice label="Added salt quantity" value={String(p.saltFactor)} options={[{value:'0',label:'No added salt'},{value:'0.5',label:'Half the recipe salt'},{value:'1',label:'As written'}]} onChange={v=>field('saltFactor',Number(v))}/></div></div>
 <div className="settings-card"><Globe size={24}/><h2>Ordering & sharing</h2><div className="form-grid"><label className="field">City / locality<input value={p.city} onChange={e=>field('city',e.target.value)} placeholder="Your delivery area"/></label><label className="field">Delivery PIN code<input inputMode="numeric" maxLength={6} value={p.postalCode} onChange={e=>field('postalCode',e.target.value)} placeholder="6 digits"/></label>{number('Family-order budget, including fees (₹)','budget',100,50000)}{number('Order-in meals per week (a guide)','orderMealsPerWeek',0,14)}<label className="field">Time zone<input value={p.timezone} onChange={e=>field('timezone',e.target.value)} placeholder="Asia/Kolkata"/></label><label className="field">Preferred sharing time<input type="time" value={p.sharingTime} onChange={e=>field('sharingTime',e.target.value)}/></label></div><p className="small-note">Choose order-in meals ad hoc. Sharing time is a saved preference, not an automatic reminder. WhatsApp still opens for you to review and send.</p></div>
 <div className="profile-save"><div><strong>Your choices, saved across devices.</strong><p>Saving refreshes unconfirmed upcoming menus. Confirmed menus keep their original plan and quantity settings.</p></div><button className="button primary" disabled={!state||busy} onClick={async()=>{const result=preferencesSchema.safeParse({...p,childAges:ages.trim()?ages.split(',').map(v=>Number(v.trim())):[],avoidIngredients:avoid.split(',').map(v=>v.trim()).filter(Boolean),weeklyProteins:p.diet==='mixed'?p.weeklyProteins:Array(7).fill('veg')});if(!result.success){setError(result.error.issues.map(i=>i.path.join('.')+': '+i.message).join('; '));return}setError('');const saved=await act({action:'preferences',preferences:result.data});if(saved)toast.success('Preferences saved. Upcoming drafts will use your choices.');}}><Check size={16}/> Save & refresh drafts</button>{error&&<p className="error-text" role="alert">{error}</p>}</div></section>;
}
