'use client';
import {useState} from 'react';
import {ArrowUpRight,Check,Copy,ShoppingBag,Info} from 'lucide-react';
import {orderIdeas,orderText,weekOrderCount,basketItems,hasBengaluruExamples} from '@/lib/orders';
import {preferences} from '@/lib/preferences';
import {dateLabel,type Meal,type State} from '@/lib/food';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {toast} from 'sonner';
export default function OrderPanel({state,date,busy,act}:{state:State|null;date:string;busy:boolean;act:(p:Record<string,unknown>)=>Promise<State|null>}){
 const [meal,setMeal]=useState<Meal>('dinner');const [subtotal,setSubtotal]=useState(''),[fees,setFees]=useState('');
 const plan=state?.plans[date];const prefs=plan?.preferences||preferences(state);const local=hasBengaluruExamples(prefs);const counted=state?weekOrderCount(state.plans,date):0;
 const haveTotal=subtotal!==''&&fees!=='';const total=Math.round((Number(subtotal)+Number(fees))*100)/100;
 return <><div className="intro"><div><p className="eyebrow">SOME DAYS, LET SOMEONE ELSE COOK.</p><h1>A night off.</h1><p>{local?'Published menu ideas near '+prefs.postalCode+', '+prefs.city:'Family basket ideas for '+(prefs.city||'your area')}. Up to ₹{prefs.budget.toLocaleString('en-IN')} all in.</p></div><span className="order-count"><ShoppingBag size={20}/>{counted} of {prefs.orderMealsPerWeek} weekly order-in meals planned</span></div><div className="order-context"><div><strong>{dateLabel(date)}</strong><p>Choose any meal. No fixed order-in days.</p></div><Select value={meal} onValueChange={value=>setMeal(value as Meal)}><SelectTrigger className="meal-select" aria-label="Meal to order"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="breakfast">Breakfast</SelectItem><SelectItem value="lunch">Lunch</SelectItem><SelectItem value="dinner">Dinner</SelectItem></SelectContent></Select><span className="small-note">Change the date in Meal planner.</span></div>
 <div className="order-disclaimer"><Info size={20}/><p>These are suggested baskets from published menus, not live quotes. {local?'':'Restaurant examples are from Bengaluru; use these dishes as a guide and find a local outlet.'} Set your exact address in Zomato and check availability, portion sizes and the final total before paying. Cook Bro does not place orders.</p></div>
 {plan?.confirmed&&<p className="error-banner">This day is confirmed. Unlock it in Meal planner before changing a meal.</p>}
 <div className="order-grid">{orderIdeas.filter(o=>(!plan?.vegetarian&&prefs.diet==='mixed')||o.protein==='veg').map(o=><article key={o.id} className="order-card"><span className="eyebrow">{o.protein==='veg'?'VEGETARIAN':o.protein.toUpperCase()}</span><h2>{o.title}</h2><p className="restaurant-name">{local?o.restaurant:'Find a local restaurant serving these dishes'}</p><ul>{basketItems(o.id,prefs.servings).map(item=><li key={item}>{item}</li>)}</ul><p className="small-note">Starting quantities for {prefs.servings} cooking servings; round up to restaurant portions. {o.notes}</p><div className="order-actions"><button className="button primary" disabled={busy||!plan||plan.confirmed} onClick={async()=>{const s=await act({action:'order',date,meal,idea:o.id});if(s)toast.success(`${meal[0].toUpperCase()+meal.slice(1)} marked as order-in. Nothing has been ordered.`);}}><Check size={16}/>{plan?.takeout?.includes(meal)&&plan.orders?.[meal]===o.id?'Planned for '+meal:'Plan for '+meal}</button><a className="button" href={local?o.url:'https://www.zomato.com/'} target="_blank" rel="noreferrer">Open Zomato <ArrowUpRight size={16}/></a></div><div className="order-links"><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(orderText(o.id,prefs));toast.success('Order idea copied.');}catch{toast.error('Copy is unavailable in this browser.');}}}><Copy size={14}/> Copy basket</button><a href={o.source} target="_blank" rel="noreferrer">Example menu source</a></div></article>)}</div>
 <section className="budget-box"><div><h2>Keep the checkout under ₹{prefs.budget.toLocaleString('en-IN')}.</h2><p>Use the amounts shown in Zomato, after discounts. Delivery, packaging, taxes and tip all count.</p></div><label className="field">Food subtotal (₹)<input type="number" min="0" step="0.01" inputMode="decimal" value={subtotal} onChange={e=>setSubtotal(e.target.value)} placeholder="From your cart"/></label><label className="field">All extra charges (₹)<input type="number" min="0" step="0.01" inputMode="decimal" value={fees} onChange={e=>setFees(e.target.value)} placeholder="Fees, taxes and tip"/></label><output className={'budget-result '+(haveTotal&&total>prefs.budget?'over':'')} aria-live="polite">{haveTotal&&Number(subtotal)>=0&&Number(fees)>=0?<><strong>₹{total.toLocaleString('en-IN')}</strong><span>{total<=prefs.budget?'Within your budget':'₹'+(total-prefs.budget).toLocaleString('en-IN')+' over budget. Reduce the basket before ordering.'}</span></>:<span>Enter both amounts to check.</span>}</output></section>
 <p className="small-note">Your weekly target is a planning guide, not a limit. Choosing an order removes that meal’s home ingredients from the shopping list; it does not reserve food, place an order, or confirm a price.</p></>;
}
