'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ChefHat,ArrowUpRight,CalendarDays,Sun,Sunset,Moon,Users,Leaf,RefreshCw,ShoppingBasket,MessageCircle,Check,Clock,LockKeyhole,BookOpen,ChevronRight,Copy,Printer,Globe,ArrowLeft,Info,ShoppingBag,Smartphone} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import OrderPanel from './order-panel';
import HouseholdForm from './household-form';
import {preferences,profileLabel,localDate} from '@/lib/preferences';
import {orderById,weekOrderCount} from '@/lib/orders';
import {recipes,byId,indiaDate,addDay,dateLabel,shopping,ingredientKey,quantity,cookMessage,substitutions,alternatives,batchCount,batchRecipe,batchSafety,cookedIds,proteinForDate,recipeName,type State,type Plan,type Meal,type Recipe} from '@/lib/food';
const meals:Meal[]=['breakfast','lunch','dinner'];
const icons={breakfast:Sun,lunch:Sunset,dinner:Moon};
type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
export default function Planner(){
 const [state,setState]=useState<State|null>(null),[selected,setSelected]=useState(indiaDate(1)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[view,setView]=useState('planner');
 const [detail,setDetail]=useState<string|null>(null),[swap,setSwap]=useState<string|null>(null),[share,setShare]=useState(false),[fullRecipes,setFullRecipes]=useState(false),[phone1,setPhone1]=useState(''),[phone2,setPhone2]=useState(''),[mutton,setMutton]=useState(false),[showGuide,setShowGuide]=useState(false),[alternativeSearch,setAlternativeSearch]=useState(''),[install,setInstall]=useState(false);
 const firstLoad=useRef(true);const busyRef=useRef(false);const stateRef=useRef(state);stateRef.current=state;
 const prefs=preferences(state);const plan=state?.plans[selected];const planPrefs=plan?.preferences||prefs;const name=(r:Recipe)=>recipeName(r,planPrefs);const pantry=state?.pantry[selected]||[];
 const load=useCallback(async()=>{setError('');setBusy(true);busyRef.current=true;try{const response=await fetch('/api/household');const value=await response.json() as State & {error?:string};if(!response.ok)throw new Error(value.error);if(firstLoad.current){setSelected(localDate(1,preferences(value).timezone));firstLoad.current=false;}setState(value);setPhone1(value.settings.phone1);setPhone2(value.settings.phone2);setMutton(value.settings.allowMutton);}catch(e){setError((e as Error).message||'Could not load your menu.');}finally{setBusy(false);busyRef.current=false;}},[]);
 useEffect(()=>{void load();if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[load]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible'&&view==='planner'&&!busyRef.current)void load()};document.addEventListener('visibilitychange',refresh);return()=>document.removeEventListener('visibilitychange',refresh)},[load,view]);
 async function act(payload:Record<string,unknown>){if(busyRef.current||!stateRef.current)return null;busyRef.current=true;setBusy(true);setError('');try{const response=await fetch('/api/household',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,revision:stateRef.current.revision})});const value=await response.json() as State & {error?:string};if(!response.ok)throw new Error(value.error);stateRef.current=value;setState(value);return value as State;}catch(e){setError((e as Error).message||'Could not save. Please retry.');return null;}finally{busyRef.current=false;setBusy(false)}}
 useEffect(()=>{if(state&&!state.plans[selected]&&!busy&&!error)void act({action:'generate',date:selected,vegetarian:false});},[selected,state,busy,error]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context)return;
  const lifecycle=new AbortController();
  const tool={name:'read_selected_cook_bro_menu',description:'Read the currently selected saved menu, quantities and shopping list. Does not change the menu or send a message.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');const p=stateRef.current?.plans[selected];if(!p)throw new Error('No saved menu is ready for this day.');return {date:p.date,confirmed:p.confirmed,meals:Object.fromEntries(meals.map(m=>[m,p.takeout?.includes(m)?{orderIn:true}:p[m].map(id=>({name:recipeName(byId[id],p.preferences||preferences(stateRef.current)),ingredients:batchRecipe(p,byId[id],p.preferences||preferences(stateRef.current)).ingredients}))])),shopping:shopping(p,p.preferences||preferences(stateRef.current))};}};
  try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[selected]);
 const items=plan?shopping(plan,planPrefs):[];const needed=items.filter(i=>!pantry.includes(ingredientKey(i)));const message=plan?cookMessage(plan,pantry,fullRecipes,planPrefs):'';
 const recipe=detail?(plan?batchRecipe(plan,byId[detail],planPrefs):byId[detail]):null;const choices=plan&&swap&&state?alternatives(plan,swap,state).filter(r=>(r.name+' '+r.cuisine+' '+r.ingredients.map(i=>i.name).join(' ')).toLowerCase().includes(alternativeSearch.toLowerCase())):[];
 async function copy(text:string){try{await navigator.clipboard.writeText(text);toast.success('Copied. Ready to paste into WhatsApp.');}catch{toast.error('Copy is unavailable here. Select the message text and copy it.');}}
 async function changeRecipe(id:string){if(!swap)return;const updated=await act({action:'swap',date:selected,id:swap,replacement:id});if(updated){setSwap(null);setDetail(null);toast.success('Dish replaced. Shopping quantities updated.');}}
 const tomorrow=localDate(1,prefs.timezone);const title=selected===tomorrow?'Tomorrow, sorted.':selected===localDate(0,prefs.timezone)?'Today, sorted.':'A good day of food.';
 const formatWeek=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-IN',{weekday:'short',timeZone:'Asia/Kolkata'});
 return <Tabs value={view} onValueChange={setView} className="shell"><Toaster position="bottom-center" richColors/><header className="topbar"><a className="brand" href="/" aria-label="Cook Bro home"><span className="brand-icon"><ChefHat size={25}/></span>cook bro<span className="brand-dot">.</span></a><TabsList className="nav-list" aria-label="Main navigation"><TabsTrigger value="planner"><CalendarDays size={16}/>Meal planner</TabsTrigger><TabsTrigger value="orders"><ShoppingBag size={16}/>Order in</TabsTrigger><TabsTrigger value="household"><Users size={16}/>Household</TabsTrigger></TabsList><button className="text-button install-button" onClick={()=>setInstall(true)}><Smartphone size={17}/> Install app</button></header>
 <main><TabsContent value="planner"><div className="intro"><div><p className="eyebrow">A LITTLE PLANNING. A HAPPIER KITCHEN.</p><h1>{title}</h1><p>Many cuisines. One family table. One less thing to decide.</p></div><button className="button primary" disabled={!plan} onClick={()=>setShare(true)}><MessageCircle size={18}/> Share on WhatsApp <ArrowUpRight size={17}/></button></div>
 {error&&<div role="alert" className="error-banner">{error} <button className="text-button" onClick={load}>Reload saved menus</button></div>}
 <div className="layout"><section><div className="week-strip" aria-label="Choose a meal date">{Array.from({length:8},(_,n)=>addDay(localDate(0,prefs.timezone),n)).map((d,n)=><button key={d} onClick={()=>setSelected(d)} aria-pressed={selected===d} disabled={busy} className={selected===d?'selected':''}><span>{n===0?'Today':n===1?'Tomorrow':formatWeek(d)}</span><strong>{Number(d.slice(-2))}</strong><span className={'day-dot '+(state?.plans[d]?.confirmed?'confirmed':state?.plans[d]?'planned':'')}/></button>)}</div>
 <div className="daybar"><span><CalendarDays size={18}/>{dateLabel(selected)}</span><span className="tag">{plan?.confirmed?<><LockKeyhole size={12}/> Confirmed</>:busy?'Saving…':plan?'Saved menu':'Preparing menu'}</span></div>
 <Tabs defaultValue="menu"><TabsList className="content-tabs"><TabsTrigger value="menu"><BookOpen size={16}/> The menu</TabsTrigger><TabsTrigger value="shopping"><ShoppingBasket size={16}/> Shopping list {plan&&<span className="count">{needed.length}</span>}</TabsTrigger></TabsList>
 <TabsContent value="menu"><div className="batch-summary"><strong>{planPrefs.sharedCurry?'Cook once. Enjoy twice.':'A fresh curry at each meal.'}</strong><p>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,n)=>d+': '+(planPrefs.diet==='mixed'?planPrefs.weeklyProteins[n]:'veg')).join(' · ')}</p><span className="small-note">Change your weekly rhythm in Household. Vegetarian today overrides the day’s protein.</span></div><div className="menu-options"><label className="check-label"><Checkbox checked={plan?.vegetarian||false} disabled={!plan||busy||plan.confirmed} onCheckedChange={async value=>{const s=await act({action:'generate',date:selected,vegetarian:!!value});if(s)toast.success(value?'Vegetarian menu saved.':'Mixed-cuisine menu saved.');}}/> Vegetarian today <span className="small-note">(no eggs)</span></label><button className="text-button" disabled={!plan||busy||plan.confirmed} onClick={()=>act({action:'generate',date:selected,vegetarian:plan?.vegetarian||false})}><RefreshCw size={14}/> New menu</button></div>
 {!plan?<div className="empty-state" role="status"><ChefHat size={30}/><h2>{error?'Your menu is unavailable':'Setting the table…'}</h2><p>{error?'Retry to load your saved household.':'Finding a little variety for your day.'}</p></div>:meals.map(meal=>{const Icon=icons[meal],rs=plan[meal].map(id=>byId[id]),isOut=plan.takeout?.includes(meal),idea=plan.orders?.[meal]?orderById[plan.orders[meal]!]:null;return <article className={'meal-card '+(meal==='lunch'?'lunch':'')} key={meal}><div className="meal-label"><Icon size={20}/><span>{meal.toUpperCase()}</span><span className="time"><Clock size={13}/> {rs.length===1?rs[0].minutes:Math.max(...rs.map(r=>r.minutes))+'–'+rs.reduce((n,r)=>n+r.minutes,0)} min*</span></div><div className="meal-mode"><button className="text-button" disabled={busy||plan.confirmed} onClick={()=>act({action:'takeout',date:selected,meal,enabled:!isOut})}>{isOut?<><ChefHat size={15}/> Cook at home instead</>:<><ShoppingBag size={15}/> Order this meal instead</>}</button></div>{isOut?<div className="takeout-meal"><h2>{idea?.title||'Taking this meal off.'}</h2><p>{idea?.restaurant||'Choose a family basket in Order in.'}</p><p className="small-note">No home ingredients counted for this meal. Planned only, not ordered.</p><button className="button" onClick={()=>setView('orders')}>See Zomato ideas <ArrowUpRight size={16}/></button></div>:<>{meal==='breakfast'?<><div className="dish-heading"><h2>{name(rs[0])}</h2><button aria-label={'Alternatives to '+name(rs[0])} className="swap-button" disabled={busy||plan.confirmed} onClick={()=>(setAlternativeSearch(''),setSwap(rs[0].id))}><RefreshCw size={16}/></button></div><div className="chips"><span><Globe size={12}/>{rs[0].cuisine}</span><span>No added sugar</span></div><button className="text-button" onClick={()=>setDetail(rs[0].id)}>Recipe & quantities <ArrowUpRight size={15}/></button></>:<><h2>{meal==='lunch'?'A satisfying lunch.':'Dinner, already considered.'}</h2><div className="dish-list">{rs.map(r=><div className="dish-row" key={r.id}><span className="dish-kind">{r.kind==='grain'?'STAPLE':r.kind==='bhaja'?'SIDE':r.kind.toUpperCase()}</span><button className="dish-name" onClick={()=>setDetail(r.id)}><span>{name(r)}</span><small>{r.kind==='curry'&&plan.sharedCurry?(meal==='dinner'?'From the afternoon batch':batchCount(plan,r.id)>1?'Cook once for lunch + dinner':'Cook for this meal only'):r.cuisine}</small></button>{r.kind!=='grain'&&<button className="swap-button" disabled={busy||plan.confirmed} aria-label={'Alternatives to '+name(r)} onClick={()=>(setAlternativeSearch(''),setSwap(r.id))}><RefreshCw size={15}/></button>}<button className="recipe-arrow" aria-label={'Recipe and quantities for '+name(r)} onClick={()=>setDetail(r.id)}><ChevronRight size={17}/></button></div>)}</div></>}</>}<div className="meal-footer"><Users size={13}/> {planPrefs.servings} cooking servings · {profileLabel(planPrefs)}{meal!=='breakfast'&&<span>Lightly cooked side</span>}</div></article>})}
 <p className="timing-note">*Cooking-time range assumes dishes cook together or one after another. Soaking and dough resting may add time.</p>
 {plan&&<div className="confirm-row"><div><strong>{plan.confirmed?'Decision made. Kitchen sorted.':'Happy with the menu?'}</strong><p>{plan.confirmed?'Unlock it whenever you want to make a change.':'Confirm it before sharing with your cook.'}</p></div><button className={'button '+(!plan.confirmed?'primary':'')} disabled={busy} onClick={async()=>{const s=await act({action:'confirm',date:selected,confirmed:!plan.confirmed});if(s)toast.success(plan.confirmed?'Menu unlocked.':'Menu confirmed.');}}>{plan.confirmed?<><LockKeyhole size={16}/> Unlock menu</>:<><Check size={16}/> Confirm menu</>}</button></div>}
 </TabsContent><TabsContent value="shopping"><div className="shopping-intro"><h2>What’s needed in the kitchen</h2><p>Combined quantities for home-cooked meals only. A shared curry includes both meals; order-in meals are excluded. Tick an item only if you have enough for the day.</p><div className="shopping-summary"><span><strong>{needed.length}</strong> to buy</span><span><strong>{items.length-needed.length}</strong> already at home</span><button className="text-button" disabled={!plan} onClick={()=>copy(needed.map(i=>`${i.name}: ${quantity(i)}`).join('\n'))}><Copy size={14}/> Copy list</button></div></div>{[...new Set(items.map(i=>i.category))].map(category=><div className="shopping-group" key={category}><h3>{category}</h3>{items.filter(i=>i.category===category).map(i=><label key={ingredientKey(i)} className={'shopping-item '+(pantry.includes(ingredientKey(i))?'have':'')}><Checkbox disabled={busy} checked={pantry.includes(ingredientKey(i))} onCheckedChange={checked=>act({action:'pantry',date:selected,key:ingredientKey(i),checked:!!checked})}/><span>{i.name}</span><strong>{quantity(i)}</strong></label>)}</div>)}<p className="small-note">Water is not included. Dry pulses and cooked pulses are listed separately. Quantities are cooking starting points, not prescribed serving sizes.</p></TabsContent></Tabs>
 </section><aside><div className="photo-card"><img src="https://upload.wikimedia.org/wikipedia/commons/b/bd/Fish_And_Rice.jpg" alt="Indian home-style meal with rice, fish, dal and vegetable sides" width="4097" height="2404"/><div><p className="eyebrow">ROOTED AT HOME. CURIOUS ABOUT FOOD.</p><h2>A world at your table.</h2><p>Punjabi comfort. South Indian favourites. A little Italian, French and more.</p><span className="photo-caption">Serving inspiration, not the selected menu.</span></div></div><div className="side-card variety"><Globe size={23}/><h3>Familiar rhythm. Fresh choices.</h3><p>{planPrefs.lunchStaple} at lunch. {planPrefs.dinnerStaple} at dinner. {planPrefs.includeDal?'Dal included. ':''}{planPrefs.includeSide?'A lightly cooked vegetable side.':''}</p><div className="rule-line"><Check size={15}/><span>No repeats on different days within {planPrefs.repeatDays} days. {planPrefs.sharedCurry?'One curry is shared across the same day.':'Separate lunch and dinner curries.'}</span></div><p className="small-note">Swaps keep the day’s protein. Older menus are considered for 20 days. Customize cuisines, portions and ingredients in Household.</p></div><div className="side-card"><Leaf size={23}/><h3>One kitchen. Different needs.</h3><p>Measured oil and salt, no added sugar, and serving notes for adults, children and elders.</p><button className="text-button" onClick={()=>setShowGuide(true)}>Family serving guide <ArrowUpRight size={15}/></button></div><div className="side-card whatsapp"><MessageCircle size={23}/><h3>Tomorrow’s menu, tonight.</h3><p>Share around {prefs.sharingTime} ({prefs.timezone}), so your cook has time to prepare.</p><span className="status">Manual sharing · no automatic messages</span><button className="text-button" disabled={!plan} onClick={()=>setShare(true)}>Open sharing options <ArrowUpRight size={15}/></button></div></aside></div>
 </TabsContent>
 <TabsContent value="orders"><OrderPanel state={state} date={selected} busy={busy} act={act}/>{error&&<p role="alert" className="error-banner">{error}</p>}</TabsContent><TabsContent value="household"><div className="intro"><div><p className="eyebrow">THE PEOPLE AROUND YOUR TABLE</p><h1>Our household.</h1><p>One shared meal. Enough flexibility for everyone.</p></div></div><HouseholdForm state={state} busy={busy} act={act}/><div className="settings-grid"><section className="settings-card"><Users size={25}/><h2>Occasional mutton</h2><label className="check-label"><Checkbox checked={mutton} onCheckedChange={v=>setMutton(!!v)}/> Allow mutton in mixed menus</label><p className="small-note">Off by default. When enabled, an occasional Sunday may use mutton, at most once in 14 days. Save sharing settings below to apply.</p><button className="text-button" onClick={()=>setShowGuide(true)}>Family serving guidance <ArrowUpRight size={16}/></button></section><section className="settings-card"><MessageCircle size={25}/><h2>Make sharing easier</h2><p>Optional WhatsApp numbers for you and your partner. They stay in your private household and are used only when you choose to open WhatsApp.</p><label className="field">Your WhatsApp number<input type="tel" autoComplete="tel" value={phone1} onChange={e=>setPhone1(e.target.value)} placeholder="+91 followed by 10 digits"/></label><label className="field">Partner’s WhatsApp number<input type="tel" autoComplete="off" value={phone2} onChange={e=>setPhone2(e.target.value)} placeholder="+91 followed by 10 digits"/></label><p className="small-note">Use international format, with no spaces. You can also choose any chat or family group in ordinary WhatsApp.</p><button className="button primary" disabled={busy||!state} onClick={async()=>{const s=await act({action:'settings',phone1:phone1.trim(),phone2:phone2.trim(),allowMutton:mutton});if(s)toast.success('Household preferences saved.');}}><Check size={16}/> Save preferences</button>{error&&<p className="error-text" role="alert">{error}</p>}<div className="delivery-note"><Clock size={19}/><div><strong>{prefs.sharingTime} is a sharing preference, not a scheduled send.</strong><p>This version uses ordinary WhatsApp. You review the message and press Send there. No Business account is needed.</p></div></div></section></div></TabsContent>
 </main><footer><span>Cook Bro · Less deciding. More enjoying.</span><button className="text-button" onClick={()=>setShowGuide(true)}>Nutrition guidance & sources</button><span className="credit">Photo: <a href="https://commons.wikimedia.org/wiki/File:Fish_And_Rice.jpg" target="_blank" rel="noreferrer">শক্তিশেল / Wikimedia Commons</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a> · Cropped</span></footer>
 <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="detail-dialog">{recipe&&<><DialogTitle className="dialog-heading">{name(recipe)}</DialogTitle><DialogDescription>{recipe.cuisine} · {recipe.minutes} min base recipe · {plan&&batchCount(plan,recipe.id)>1?'One larger batch for lunch + dinner':'Family batch for one meal'}</DialogDescription><div className="dialog-body"><div className="recipe-metadata"><span>No added sugar</span><span>Allergens: {recipe.allergens.length?recipe.allergens.join(', '):'check ingredient labels'}</span></div><h3>Ingredients & quantities</h3><p className="small-note">{plan&&batchCount(plan,recipe.id)>1?`Already scaled for two meals, ${planPrefs.servings} cooking servings each. Refrigerate dinner promptly.`:`For one meal, ${planPrefs.servings} cooking servings.`} These are cooking quantities, not individual serving prescriptions.</p><ul className="ingredients">{recipe.ingredients.map((i,n)=><li key={n}><span>{i.name}</span><strong>{quantity(i)}</strong></li>)}</ul>{plan&&batchCount(plan,recipe.id)>1&&<div className="recipe-note"><Info size={18}/><p>{batchSafety}</p></div>}<h3>Let’s cook</h3><ol className="steps">{recipe.steps.map((step,n)=><li key={n}><span>{n+1}</span><p>{step}</p></li>)}</ol><div className="recipe-note"><Info size={18}/><p>{recipe.note}</p></div>{recipe.ingredients.some(i=>substitutions[i.name])&&<><h3>Missing an ingredient?</h3><div className="substitutions">{recipe.ingredients.filter(i=>substitutions[i.name]).map((i,n)=><p key={n}><strong>{i.name}:</strong> {substitutions[i.name]}</p>)}</div><p className="small-note">These are cooking suggestions. A substitution can change allergens and nutrition. The shopping list updates when you replace a whole dish, not when you make a substitution yourself.</p></>}{recipe.kind!=='grain'&&<button className="button" disabled={plan?.confirmed||busy} onClick={()=>{setAlternativeSearch('');setSwap(recipe.id);setDetail(null);}}><RefreshCw size={16}/> Choose an alternative dish</button>}</div></>}</DialogContent></Dialog>
 <Dialog open={!!swap} onOpenChange={open=>!open&&setSwap(null)}><DialogContent className="detail-dialog"><DialogTitle className="dialog-heading">A different kind of delicious.</DialogTitle><DialogDescription>Replace {swap?name(byId[swap]):''}. These choices avoid dishes on nearby days and keep the day’s protein. A shared curry swap updates both meals.</DialogDescription><label className="field alternative-search">Find a dish, cuisine or ingredient<input type="search" value={alternativeSearch} onChange={e=>setAlternativeSearch(e.target.value)} placeholder="Try paneer, Punjabi, fish or Italian"/></label><div className="dialog-body alternative-list">{choices.length?choices.map(r=><div className="alternative" key={r.id}><div><span className="eyebrow">{r.cuisine}</span><h3>{name(r)}</h3><p>{r.ingredients.slice(0,4).map(i=>i.name).join(' · ')}</p><span className="small-note">{r.minutes} min · {r.allergens.length?'Contains '+r.allergens.join(', '):'Check ingredient labels'}</span></div><button className="button" disabled={busy} onClick={()=>changeRecipe(r.id)}>Use this <Check size={14}/></button></div>):<p>No matching unused dish. Try another search, or keep the current dish.</p>}</div>{error&&<p className="error-text" role="alert">{error}</p>}</DialogContent></Dialog>
 <Dialog open={share} onOpenChange={setShare}><DialogContent className="detail-dialog share-dialog"><DialogTitle className="dialog-heading">Ready for the kitchen.</DialogTitle><DialogDescription>{plan?dateLabel(plan.date):''} · {plan?.confirmed?'Confirmed menu':'Suggested menu, not yet confirmed'}</DialogDescription><div className="dialog-body"><p>The message includes your menu, quantities and items still to buy. Medical details and phone numbers are never included.</p><label className="check-label"><Checkbox checked={fullRecipes} onCheckedChange={v=>setFullRecipes(!!v)}/> Include full recipes</label><textarea className="message-preview" readOnly value={message} aria-label="WhatsApp message preview" rows={10}/><div className="share-actions"><button className="button" onClick={()=>copy(message)}><Copy size={16}/> Copy message</button><button className="button" onClick={()=>{setShare(false);setTimeout(()=>window.print(),150)}}><Printer size={16}/> Print cook sheet</button></div>{message.length<6500?<><a className="button primary wide" href={'https://wa.me/?text='+encodeURIComponent(message)} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Open WhatsApp · choose a chat <ArrowUpRight size={16}/></a><div className="share-actions">{state?.settings.phone1&&<a className="button" href={'https://wa.me/'+state.settings.phone1.slice(1)+'?text='+encodeURIComponent(message)} target="_blank" rel="noreferrer">Send to my number</a>}{state?.settings.phone2&&<a className="button" href={'https://wa.me/'+state.settings.phone2.slice(1)+'?text='+encodeURIComponent(message)} target="_blank" rel="noreferrer">Send to my partner</a>}</div></>:<div className="recipe-note"><Info size={18}/><p>Full recipes make a long message. Use “Copy message” and paste it into WhatsApp, or print the cook sheet.</p></div>}<p className="small-note">Nothing is sent automatically. WhatsApp opens for you to review and press Send. For both of you, choose your family group or share to each number.</p></div></DialogContent></Dialog>
 <Dialog open={showGuide} onOpenChange={setShowGuide}><DialogContent className="detail-dialog"><DialogTitle className="dialog-heading">One meal, thoughtfully served.</DialogTitle><DialogDescription>General meal-planning guidance, not a prescribed diet.</DialogDescription><div className="dialog-body guidance"><h3>Adults: build a balanced plate</h3><p>Use plenty of non-starchy vegetables, a protein food, and a moderate amount of rice or roti. Dal also contributes carbohydrates. Individual portions depend on appetite, activity, glucose response and your clinician’s advice.</p><h3>Children: support growth</h3><p>Start with smaller, age-appropriate portions and offer more when hungry. Do not apply an adult weight-loss diet to children. Debone fish carefully, mash beans for the youngest, and serve soft pieces. Avoid whole nuts and other choking hazards.</p><h3>Older adults: keep food easy to eat</h3><p>Offer soft rotis, well-cooked dal, tender vegetables and easy-to-chew protein. Adjust texture to their needs. A clinician should guide any kidney, swallowing or other prescribed diet.</p><h3>Flavour without the extras</h3><p>All recipes avoid added sugar and use measured oil and salt. WHO recommends adults keep total salt below 5 g a day, including salt in packaged foods; children need less according to their energy needs. Recipe salt is a batch amount, not an individual daily allowance. Avoid adding pickles, salty sauces or extra table salt routinely.</p><h3>Save the dinner portion safely</h3><p>{batchSafety}</p><p><a href="https://www.fda.gov/food/buy-store-serve-safe-food/serving-safe-buffets" target="_blank" rel="noreferrer">FDA: storing cooked food safely</a></p><h3>A plan that fits your care</h3><p>Medication and treatment can affect food needs. Review a typical week with your doctor or dietitian, particularly during weight treatment or if appetite or weight changes quickly. Cook Bro does not change medicines, set weight-loss targets or calculate a medical diet. Ingredient and allergen filters match the recipe catalogue; they cannot verify packaging, substitutions or cross-contact.</p><h3>Sources & recipe notes</h3><p><a href="https://diabetes.org/food-nutrition/meal-planning" target="_blank" rel="noreferrer">American Diabetes Association: meal planning</a></p><p><a href="https://www.who.int/news-room/fact-sheets/detail/healthy-diet" target="_blank" rel="noreferrer">World Health Organization: healthy diet</a></p><p>Recipes are original home-cooking adaptations, not clinician-reviewed or live web search results. Quantities and times are practical starting estimates. No calorie, carbohydrate or sodium totals are claimed.</p></div></DialogContent></Dialog>
 <Dialog open={install} onOpenChange={setInstall}><DialogContent className="detail-dialog"><DialogTitle className="dialog-heading">Cook Bro, on every screen.</DialogTitle><DialogDescription>An installable web app for iPhone, iPad and Mac. No App Store download required.</DialogDescription><div className="dialog-body install-guide"><img src="/apple-touch-icon.png" width="72" height="72" alt="Cook Bro app icon"/><h3>iPhone or iPad</h3><p>Open this private app in Safari. Tap Share, then Add to Home Screen. If shown, keep “Open as Web App” enabled and tap Add.</p><h3>Mac, Mac mini or MacBook</h3><p>On macOS Sonoma or later, open the app in Safari and choose File → Add to Dock. On older macOS, use it in your browser.</p><h3>Your plans stay together</h3><p>Sign in with the same ChatGPT account on each device. Menus, shopping checks and household preferences are saved online. An internet connection is needed; private meal data is not cached for offline use.</p><p className="small-note">Installing does not enable automatic WhatsApp messages or reminders. This site is private to your account; share the menu text with family and your cook.</p><p><a href="https://support.apple.com/en-us/104996" target="_blank" rel="noreferrer">Apple’s Mac installation guide</a></p></div></DialogContent></Dialog>
 {plan&&<section className="print-sheet"><h1>Cook Bro · {dateLabel(plan.date)}</h1><pre>{cookMessage(plan,pantry,true,planPrefs)}</pre></section>}
 </Tabs>;
}
