import {preferences,defaultPreferences,profileLabel,type Preferences} from './preferences';
export type Ingredient = { name: string; qty: number; unit: string; category: string };
export type Recipe = { id: string; name: string; kind: 'breakfast'|'dal'|'curry'|'bhaja'|'grain'; protein: 'veg'|'fish'|'chicken'|'mutton'; minutes: number; ingredients: Ingredient[]; steps: string[]; note: string; allergens: string[]; englishName?:string; cuisine?:string };
const i=(name:string,qty:number,unit='g',category='Vegetables'):Ingredient=>({name,qty,unit,category});
const oil=(n=10)=>i('Cooking oil',n,'ml','Pantry');
const salt=(n=1)=>i('Salt',n,'g','Pantry');
const spice=(name:string,n=.5)=>i(name,n,'tsp','Pantry');
const onion=()=>i('Onion',150);
const tomato=()=>i('Tomato',200);
const ginger=()=>i('Ginger',15);
const garlic=()=>i('Garlic',15);
const lentil=(name:string,n=240)=>i(name,n,'g','Grains & pulses');
const dairy=(name:string,n:number)=>i(name,n,'g','Dairy & eggs');
const vegNote='Keep chillies optional. Cook until tender; offer soft, bite-sized pieces to younger children.';
const base=(id:string,name:string,kind:Recipe['kind'],minutes:number,ingredients:Ingredient[],steps:string[],note=vegNote,protein:Recipe['protein']='veg',allergens:string[]=[]):Recipe=>({id,name,kind,minutes,ingredients,steps,note,protein,allergens});
function dal(id:string,name:string,pulse:string,vegetable:string){return base(id,name,'dal',pulse==='Chana dal'||pulse==='Toor dal'?45:35,[lentil(pulse),i(vegetable,450),ginger(),oil(),salt(),spice('Cumin seeds'),spice('Turmeric',.5)],['Rinse the dal. Simmer with 1.2 litres water and turmeric until soft, adding water as needed. Chana or toor dal may take 45 minutes.','Add chopped vegetables and cook until tender. Stir often; mash lightly for a soft texture.','Warm the measured oil, bloom cumin and ginger, then stir into the dal. Add the measured salt and simmer for 3 minutes.']);}
function bhaja(id:string,name:string,vegetable:string){return base(id,name,'bhaja',25,[i(vegetable,900),oil(15),salt(.5),spice('Turmeric',.5),spice('Cumin seeds')],['Wash, dry and slice the vegetables. For okra, dry thoroughly before cutting.','Warm the measured oil in a wide nonstick pan and add cumin. Add vegetables and turmeric; cook in batches if crowded.','Cook on medium heat, turning often, until tender and lightly browned, about 15–20 minutes. Use a splash of water if sticking. Add measured salt. No deep frying.']);}
function vegCurry(id:string,name:string,ingredients:Ingredient[],steps:string[],allergens:string[]=[]){return base(id,name,'curry',35,[...ingredients,onion(),tomato(),ginger(),garlic(),oil(15),salt(),spice('Cumin seeds'),spice('Turmeric',.5),spice('Coriander powder',1)],['Heat the measured oil. Add cumin, chopped onion, ginger and garlic. Cook gently for 5 minutes. Add tomato, turmeric and coriander; cook until soft.',...steps,'Add measured salt and simmer until tender. Keep the gravy loose; add water as needed.'],vegNote,'veg',allergens);}
const fishNote='Cook fish to 63°C at its thickest point. Carefully remove all bones before serving children or anyone with chewing difficulty. Mustard can cause allergy.';
const chickenNote='Cook chicken to 74°C at its thickest point. Keep raw meat separate from ready-to-eat food. Remove bones and shred for young children.';
function fish(id:string,name:string,extra:Ingredient[],method:string){return base(id,name,'curry',35,[i('Fish (rui or boneless white fish)',900,'g','Fish & meat'),...extra,ginger(),oil(15),salt(),spice('Turmeric',.5),spice('Cumin seeds')],['Pat fish dry and rub with turmeric. Heat measured oil and cumin in a wide pan; add ginger.',method,'Slide in fish and simmer gently 10–15 minutes, until the thickest part reaches 63°C. Add measured salt. Debone each child’s portion carefully.'],fishNote,'fish',['Fish',...(id==='shorshe-fish'?['Mustard']:[])]);}
export const recipes:Recipe[]=[
base('chilla','Moong dal chilla & plain curd','breakfast',30,[lentil('Split moong dal',300),i('Carrot',200),i('Cucumber',300),dairy('Plain unsweetened curd',500),ginger(),oil(15),salt()],['Soak moong dal for 4 hours or overnight in the fridge. Drain and blend with ginger and enough water for a pourable batter.','Stir grated carrot and measured salt into the batter. Use the measured oil to cook small chillas on both sides until set and golden.','Serve with plain unsweetened curd and cucumber. Grate cucumber for the youngest child.'],'Soak tonight. Active cooking: 30 minutes. Keep portions flexible.','veg',['Milk']),
base('poha','Vegetable chire & plain curd','breakfast',25,[lentil('Thick poha (chire)',300),i('Carrot',250),i('Green peas',200),onion(),dairy('Plain unsweetened curd',500),oil(15),salt(),spice('Mustard seeds')],['Rinse poha quickly and drain for 5 minutes.','Warm oil, add mustard seeds, onion, carrot and peas. Cook with a splash of water until tender.','Fold in poha and measured salt. Steam covered for 4 minutes. Serve with unsweetened curd.'],vegNote,'veg',['Milk','Mustard']),
base('oats','Savoury vegetable oats & eggs','breakfast',25,[lentil('Rolled oats',300),i('Carrot',250),i('Green peas',200),i('Eggs',6,'pcs','Dairy & eggs'),oil(),salt(),spice('Cumin seeds')],['Cook eggs in boiling water until yolks and whites are firm, about 10–12 minutes. Peel and cut into small pieces for children.','Warm oil and cumin, add finely chopped carrot and peas. Cook until tender.','Add oats and 1.1 litres water. Simmer 8–10 minutes, stirring. Add measured salt; serve with the eggs.'],'Eggs must be fully cooked. Oats may contain gluten; check the pack.','veg',['Egg','Gluten']),
base('besan','Besan vegetable pancakes','breakfast',25,[lentil('Besan',300),i('Spinach',200),i('Tomato',150),dairy('Plain unsweetened curd',500),oil(15),salt(),spice('Cumin powder')],['Whisk besan with 500 ml water to make a smooth batter. Rest 10 minutes.','Add finely chopped spinach and tomato, cumin and measured salt.','Cook small pancakes with the measured oil until set on both sides. Serve with plain curd.'],vegNote,'veg',['Milk']),
base('dalia','Savoury dalia khichuri','breakfast',35,[lentil('Broken wheat (dalia)',250),lentil('Split moong dal',150),i('Carrot',250),i('Green beans',250),ginger(),oil(),salt(),spice('Cumin seeds')],['Rinse dalia and dal. Warm oil with cumin and ginger.','Add chopped vegetables, dalia and dal with 1.5 litres water. Simmer covered for 25–30 minutes until soft.','Add measured salt and water if needed. Serve warm with a spoon, especially for the youngest child.'],vegNote,'veg',['Wheat']),
base('idli','Idli with vegetable sambar','breakfast',40,[i('Unsalted idli batter',750,'g','Grains & pulses'),lentil('Toor dal',200),i('Carrot',200),i('Bottle gourd',250),tomato(),oil(),salt(),spice('Cumin seeds'),spice('Turmeric')],['Steam idlis in lightly oiled moulds for 12–15 minutes until cooked through.','Simmer washed toor dal in 1 litre water for 30–40 minutes until soft. Add chopped vegetables, tomato and turmeric; cook until tender.','Temper cumin in the remaining measured oil, stir into the dal and add measured salt. Serve with the idlis.'],'Choose unsalted batter or reduce added salt to account for the pack label. Dal cooking can run alongside steaming.'),
base('egg-roti','Egg bhurji & soft rotis','breakfast',30,[i('Eggs',6,'pcs','Dairy & eggs'),lentil('Whole-wheat atta',300),i('Tomato',200),onion(),i('Spinach',200),oil(),salt()],['Knead atta with about 200 ml water. Rest 10 minutes, then roll 10–12 small rotis and cook on a hot tawa.','Cook onion, tomato and chopped spinach in measured oil until soft.','Whisk eggs with measured salt, add to the pan and scramble until fully set. Serve with soft rotis.'],chickenNote.replace('Cook chicken to 74°C at its thickest point.','Cook eggs until the white and yolk are firm.').replace('Remove bones and shred for young children.','Cut into small pieces for young children.'),'veg',['Egg','Wheat']),
base('uttapam','Vegetable uttapam & curd','breakfast',30,[i('Unsalted idli batter',700,'g','Grains & pulses'),i('Carrot',200),i('Tomato',200),onion(),dairy('Plain unsweetened curd',500),oil(15),salt(.5)],['Mix grated carrot and finely chopped onion and tomato into the batter. Add measured salt only if the batter is unsalted.','Make small thick pancakes on a nonstick pan using the measured oil. Cover and cook, then flip until the centre is fully set.','Serve with plain unsweetened curd.'],vegNote,'veg',['Milk']),
dal('lau-moong','Lau diye moong dal','Split moong dal','Bottle gourd'),dal('masoor','Tomato masoor dal','Red masoor dal','Tomato'),dal('palong-dal','Palong masoor dal','Red masoor dal','Spinach'),dal('lebu-dal','Lebu moong dal','Split moong dal','Courgette'),dal('cholar','Cholar dal with vegetables','Chana dal','Carrot'),dal('toor','Vegetable toor dal','Toor dal','Pumpkin'),dal('methi-dal','Methi moong dal','Split moong dal','Fenugreek leaves'),dal('mixed-dal','Mixed vegetable masoor dal','Red masoor dal','Green beans'),
fish('rui-jhol','Rui macher jhol',[i('Cauliflower',450),tomato()],'Add chopped tomato and cauliflower with 500 ml water. Simmer until the vegetables are almost tender.'),
fish('shorshe-fish','Shorshe maach',[spice('Mustard seeds',2),i('Aubergine',400)],'Soak mustard seeds for 20 minutes and blend smooth with water. Add mustard paste, sliced aubergine and 450 ml water; simmer until aubergine is soft.'),
fish('doi-fish','Doi maach',[dairy('Plain unsweetened curd',250),onion()],'Soften sliced onion in the oil. Lower the heat and slowly stir in whisked curd with 300 ml water; avoid a rolling boil.'),
fish('tomato-fish','Tomato dhonepata maach',[i('Tomato',400),i('Fresh coriander',30)],'Add chopped tomato and coriander with 400 ml water. Simmer for 10 minutes to make a light gravy.'),
base('chicken-jhol','Light chicken jhol','curry',45,[i('Skinless boneless chicken',900,'g','Fish & meat'),i('Carrot',350),onion(),tomato(),ginger(),garlic(),oil(15),salt(),spice('Turmeric'),spice('Coriander powder',1)],['Warm oil and soften chopped onion, ginger and garlic. Add tomato and ground spices; cook for 5 minutes.','Add chicken and carrot. Stir for 3 minutes, add 450 ml water and simmer covered for 25–30 minutes.','Add measured salt. Check chicken reaches 74°C, then shred or cut into small pieces as needed.'],chickenNote,'chicken'),
base('palong-chicken','Palong chicken','curry',40,[i('Skinless boneless chicken',900,'g','Fish & meat'),i('Spinach',500),onion(),ginger(),garlic(),oil(15),salt(),spice('Cumin powder'),spice('Turmeric')],['Wash and chop spinach. Soften onion, ginger and garlic in measured oil.','Add chicken, cumin, turmeric and 350 ml water. Cover and simmer for 25 minutes.','Add spinach and measured salt. Cook another 8 minutes, checking chicken reaches 74°C.'],chickenNote,'chicken'),
base('doi-chicken','Doi chicken','curry',45,[i('Skinless boneless chicken',900,'g','Fish & meat'),dairy('Plain unsweetened curd',250),i('Green beans',350),onion(),ginger(),garlic(),oil(15),salt(),spice('Cumin powder')],['Mix chicken with curd, ginger and garlic. Keep chilled until cooking.','Soften onion in measured oil. Add chicken, cumin and 350 ml water. Simmer gently for 25 minutes.','Add chopped beans and measured salt. Cook until beans are tender and chicken reaches 74°C.'],chickenNote,'chicken',['Milk']),
vegCurry('palong-paneer','Palong paneer',[i('Spinach',650),dairy('Paneer',400)],['Add washed, chopped spinach and 200 ml water. Cook until tender, then mash or blend carefully.','Add cubed paneer and warm gently for 5 minutes.'],['Milk']),
vegCurry('chana-lau','Chana & lau curry',[lentil('Cooked chickpeas, unsalted',550),i('Bottle gourd',650)],['Add peeled, cubed bottle gourd and 250 ml water. Cover and simmer until tender.','Add cooked chickpeas and simmer 8 minutes; mash chickpeas well for young children.']),
vegCurry('fulkopi','Fulkopi matar dalna',[i('Cauliflower',700),i('Green peas',300)],['Add cauliflower florets, peas and 300 ml water. Cover and simmer for 18–20 minutes.']),
vegCurry('cabbage','Bandhakopir torkari',[i('Cabbage',850),i('Green peas',250)],['Add shredded cabbage, peas and 100 ml water. Cover and cook for 15–20 minutes, stirring occasionally.']),
vegCurry('rajma','Rajma with vegetables',[lentil('Cooked kidney beans, unsalted',650),i('Carrot',400)],['Add carrot and 250 ml water; simmer until tender.','Add fully cooked kidney beans and simmer 10 minutes. Mash beans for young children. Use canned unsalted beans or beans boiled vigorously before simmering; never use raw or undercooked kidney beans.']),
vegCurry('soy','Soya vegetable jhol',[lentil('Dry soya chunks',200),i('Cauliflower',500)],['Boil soya chunks in water for 10 minutes or follow the pack instructions. Drain, rinse and squeeze; cut small.','Add soya and cauliflower with 350 ml water. Simmer until cauliflower is tender.'],['Soy']),
vegCurry('beans-paneer','Beans & paneer curry',[i('Green beans',600),dairy('Paneer',350)],['Add chopped beans and 300 ml water, cover and simmer until tender.','Add paneer cubes and simmer 5 minutes.'],['Milk']),
vegCurry('egg-curry','Dimer light jhol',[i('Eggs',6,'pcs','Dairy & eggs'),i('Cauliflower',500)],['Hard-boil eggs until yolks and whites are firm, about 10–12 minutes. Peel and quarter.','Add cauliflower and 300 ml water to the gravy. Simmer until tender, then add eggs and warm for 3 minutes.'],['Egg']),
base('mutton','Sunday light mutton jhol','curry',90,[i('Lean boneless mutton',650,'g','Fish & meat'),i('Carrot',400),onion(),tomato(),ginger(),garlic(),oil(15),salt(),spice('Turmeric'),spice('Coriander powder',1)],['Trim visible fat. Soften onion, ginger, garlic and tomato in measured oil. Add the spices.','Add mutton, carrot and 600 ml water. Cover and simmer 60–90 minutes until fully cooked and very tender; add water as needed.','Add measured salt. Remove any bones, shred small portions and serve alongside generous vegetables and dal.'],'Occasional option, at most once in 14 planned days. Choose a small serving of lean meat.','mutton'),
bhaja('begun','Begun pan-bhaja','Aubergine'),bhaja('bhindi','Bhindi bhaja','Okra'),bhaja('beans','Beans bhaja','Green beans'),bhaja('cabbage-bhaja','Cabbage pan-bhaja','Cabbage'),bhaja('fulkopi-bhaja','Fulkopi bhaja','Cauliflower'),bhaja('carrot-bhaja','Carrot & cumin bhaja','Carrot'),bhaja('potol','Potol bhaja','Pointed gourd'),bhaja('courgette','Courgette pan-bhaja','Courgette'),
base('rice','Steamed rice','grain',25,[lentil('Rice (dry)',300)],['Rinse rice and cook with water according to the variety’s pack instructions until tender.','Start with a modest serving alongside dal, protein and vegetables; offer more according to appetite and personal needs.'],'Rice and dal both contribute carbohydrate. Brown or parboiled rice is an optional swap, not a requirement.'),
base('roti','Soft atta rotis','grain',30,[lentil('Whole-wheat atta',400)],['Knead atta with about 260 ml water to a soft dough. Rest covered for 15 minutes.','Divide into 12–14 balls, roll thinly, and cook both sides on a hot tawa.','Wrap in a clean towel to keep soft. Serve with dal and curry.'],'Make rotis soft for children and elders; adjust portions to individual appetite.','veg',['Wheat']),
base('paratha','Methi atta parathas','grain',35,[lentil('Whole-wheat atta',400),i('Fenugreek leaves',150),oil(15)],['Wash and finely chop methi. Mix with atta and about 250 ml water, kneading into a soft dough. Rest 15 minutes.','Roll 12 small parathas. Cook on a tawa, distributing the measured oil across the batch.','Cook thoroughly on both sides. Serve soft with dal and curry.'],'Lightly brushed with oil; no extra ghee.','veg',['Wheat'])
];
// More distinct combinations keep the weekly menu varied. Staples are intentionally exempt.
const extraDals:[string,string,string,string][]=[
 ['tomato-moong','Tomato moong dal','Split moong dal','Tomato'],['lau-masoor','Lau masoor dal','Red masoor dal','Bottle gourd'],['palong-moong','Palong moong dal','Split moong dal','Spinach'],['kumro-moong','Kumro moong dal','Split moong dal','Pumpkin'],['carrot-masoor','Carrot masoor dal','Red masoor dal','Carrot'],['methi-masoor','Methi masoor dal','Red masoor dal','Fenugreek leaves'],['cabbage-moong','Cabbage moong dal','Split moong dal','Cabbage'],['beans-moong','Beans moong dal','Split moong dal','Green beans'],['lau-chana','Lau chana dal','Chana dal','Bottle gourd'],['palong-chana','Palong chana dal','Chana dal','Spinach'],['tomato-toor','Tomato toor dal','Toor dal','Tomato'],['palong-toor','Palong toor dal','Toor dal','Spinach'],['carrot-toor','Carrot toor dal','Toor dal','Carrot'],['methi-chana','Methi chana dal','Chana dal','Fenugreek leaves'],['courgette-masoor','Courgette masoor dal','Red masoor dal','Courgette'],['pumpkin-masoor','Kumro masoor dal','Red masoor dal','Pumpkin'],['cauliflower-moong','Fulkopi moong dal','Split moong dal','Cauliflower'],['cauliflower-masoor','Fulkopi masoor dal','Red masoor dal','Cauliflower'],['beans-chana','Beans chana dal','Chana dal','Green beans'],['cabbage-masoor','Cabbage masoor dal','Red masoor dal','Cabbage'],['courgette-toor','Courgette toor dal','Toor dal','Courgette'],['radish-moong','Mulo moong dal','Split moong dal','Radish']];
for(const [id,name,pulse,vegetable] of extraDals)recipes.push(dal(id,name,pulse,vegetable));
const extraBhaja:[string,string,string][]=[['pumpkin-bhaja','Kumro bhaja','Pumpkin'],['radish-bhaja','Mulo bhaja','Radish'],['bitter-gourd','Uchhe bhaja','Bitter gourd'],['ridge-gourd','Jhinge pan-bhaja','Ridge gourd'],['mushroom-bhaja','Mushroom pan-bhaja','Mushrooms'],['capsicum-bhaja','Capsicum pan-bhaja','Capsicum'],['beetroot-bhaja','Beetroot pan-bhaja','Beetroot'],['broccoli-bhaja','Broccoli pan-bhaja','Broccoli']];
for(const [id,name,veg] of extraBhaja)recipes.push(bhaja(id,name,veg));
for(const [a,b,label] of [['Cabbage','Carrot','Cabbage & carrot'],['Green beans','Carrot','Beans & carrot'],['Cauliflower','Green peas','Fulkopi & peas'],['Aubergine','Capsicum','Begun & capsicum'],['Courgette','Mushrooms','Courgette & mushroom'],['Pumpkin','Green beans','Kumro & beans'],['Pointed gourd','Carrot','Potol & carrot'],['Broccoli','Capsicum','Broccoli & capsicum'],['Okra','Onion','Bhindi & onion'],['Radish','Green peas','Mulo & peas'],['Beetroot','Carrot','Beetroot & carrot'],['Ridge gourd','Green beans','Jhinge & beans'],['Cauliflower','Capsicum','Fulkopi & capsicum'],['Cabbage','Green peas','Cabbage & peas']]){
 const r=bhaja('bhaja-'+label.toLowerCase().replaceAll(/[^a-z]+/g,'-'),label+' bhaja',a);r.ingredients[0].qty=550;r.ingredients.unshift(i(b,350));recipes.push(r);
}
for(const [id,name,protein,veg,allergy] of [
 ['chana-palong','Chana palong','chickpeas','Spinach',''],['chana-fulkopi','Chana fulkopi','chickpeas','Cauliflower',''],['chana-pumpkin','Chana kumro','chickpeas','Pumpkin',''],['chana-beans','Chana & beans','chickpeas','Green beans',''],['chana-capsicum','Chana & capsicum','chickpeas','Capsicum',''],['rajma-palong','Palong rajma','kidney beans','Spinach',''],['rajma-capsicum','Capsicum rajma','kidney beans','Capsicum',''],['rajma-lau','Lau rajma','kidney beans','Bottle gourd',''],['rajma-cabbage','Cabbage rajma','kidney beans','Cabbage',''],['paneer-methi','Methi paneer','paneer','Fenugreek leaves','Milk'],['paneer-capsicum','Capsicum paneer','paneer','Capsicum','Milk'],['paneer-fulkopi','Fulkopi paneer','paneer','Cauliflower','Milk'],['paneer-lau','Lau paneer','paneer','Bottle gourd','Milk'],['paneer-peas','Matar paneer','paneer','Green peas','Milk'],['paneer-mushroom','Mushroom paneer','paneer','Mushrooms','Milk'],['tofu-palong','Palong tofu','tofu','Spinach','Soy'],['tofu-capsicum','Capsicum tofu','tofu','Capsicum','Soy'],['tofu-beans','Beans tofu','tofu','Green beans','Soy'],['tofu-cabbage','Cabbage tofu','tofu','Cabbage','Soy'],['tofu-courgette','Courgette tofu','tofu','Courgette','Soy'],['chana-mushroom','Mushroom chana','chickpeas','Mushrooms',''],['rajma-fulkopi','Fulkopi rajma','kidney beans','Cauliflower',''],['paneer-broccoli','Broccoli paneer','paneer','Broccoli','Milk']]){
 const ingredient=protein==='paneer'?dairy('Paneer',350):protein==='tofu'?i('Tofu',450,'g','Dairy & eggs'):lentil('Cooked '+protein+', unsalted',550);
 recipes.push(vegCurry(id,name,[ingredient,i(veg,600)],[`Add chopped ${veg.toLowerCase()} with 300 ml water. Simmer until tender.`,`Add ${protein==='paneer'||protein==='tofu'?'cubed':'fully cooked'} ${protein} and simmer 8 minutes. Mash beans and cut soft pieces for young children.`],allergy?[allergy]:[]));
}
for(const [id,name,flour,veg] of [['ragi-chilla','Ragi besan chilla','Ragi flour','Carrot'],['atta-chilla','Atta besan chilla','Whole-wheat atta','Spinach'],['jowar-chilla','Jowar besan chilla','Jowar flour','Courgette'],['methi-besan','Methi besan cheela','Besan','Fenugreek leaves'],['lau-cheela','Lau besan cheela','Besan','Bottle gourd'],['cabbage-cheela','Cabbage besan cheela','Besan','Cabbage'],['tomato-cheela','Tomato besan cheela','Besan','Tomato']]){
 recipes.push(base(id,name,'breakfast',30,[lentil(flour,200),lentil('Besan',150),i(veg,350),dairy('Plain unsweetened curd',500),oil(15),salt()],['Whisk the flours with about 600 ml water into a pourable batter. Rest for 10 minutes.',`Finely grate or chop ${veg.toLowerCase()}, stir into the batter with the measured salt.`,`Cook small pancakes with the measured oil until both sides are golden and the centre is fully set. Serve with plain unsweetened curd.`],vegNote,'veg',['Milk',...(flour==='Whole-wheat atta'?['Wheat']:[])]));
}
// Familiar Indian ingredients, with different regional and international preparations.
const cuisineNames:Record<string,[string,string]>={
 'palong-paneer':['Palak paneer','Punjabi'],'chana-lau':['Chana lauki','North Indian'],'rajma':['Rajma masala','Punjabi'],'fulkopi':['Gobi matar','North Indian'],'cabbage':['Cabbage & peas sabzi','North Indian'],'beans-paneer':['Beans & paneer masala','North Indian'],'egg-curry':['Egg curry','Indian'],'methi-dal':['Methi dal','North Indian'],'palong-dal':['Dal palak','North Indian'],'toor':['Vegetable dal','South Indian'],'idli':['Idli with vegetable sambar','South Indian'],'poha':['Vegetable poha & curd','Maharashtrian'],'chilla':['Moong dal chilla & curd','North Indian'],'besan':['Besan vegetable cheela','North Indian'],'dalia':['Vegetable dalia khichdi','North Indian'],'oats':['Savoury oats & eggs','Indian'],'egg-roti':['Egg bhurji & soft rotis','North Indian'],'uttapam':['Vegetable uttapam & curd','South Indian'],
 'chana-palong':['Chana saag','Punjabi'],'chana-fulkopi':['Chana gobi','Punjabi'],'chana-pumpkin':['Chickpea & pumpkin masala','Indian'],'chana-beans':['Chickpea & green bean curry','Indian'],'chana-capsicum':['Kadai chana','North Indian'],'rajma-palong':['Rajma saag','Punjabi'],'rajma-capsicum':['Rajma & peppers','North Indian'],'rajma-lau':['Rajma lauki','North Indian'],'rajma-cabbage':['Rajma & cabbage stew','Indian'],'paneer-methi':['Methi paneer','Punjabi'],'paneer-capsicum':['Kadai paneer','Punjabi'],'paneer-fulkopi':['Gobi paneer','North Indian'],'paneer-lau':['Lauki paneer','North Indian'],'paneer-peas':['Matar paneer','Punjabi'],'paneer-mushroom':['Mushroom paneer','North Indian'],'tofu-palong':['Palak tofu','Indian'],'tofu-capsicum':['Tofu & pepper masala','Indian'],'tofu-beans':['Tofu & green bean curry','Indian'],'tofu-cabbage':['Tofu & cabbage curry','Indian'],'tofu-courgette':['Tofu & courgette curry','Indian'],'chana-mushroom':['Mushroom chana','North Indian'],'rajma-fulkopi':['Rajma gobi','North Indian'],'paneer-broccoli':['Broccoli paneer','Indian']};
for(const recipe of recipes){recipe.cuisine=recipe.kind==='grain'?'Everyday staple':'Bengali';if(cuisineNames[recipe.id]){recipe.name=cuisineNames[recipe.id][0];recipe.cuisine=cuisineNames[recipe.id][1];}else if(recipe.kind==='dal'&&!['lau-moong','cholar','masoor','lebu-dal'].includes(recipe.id)){recipe.cuisine='Indian';recipe.name=recipe.name.replaceAll('Palong','Spinach').replaceAll('Kumro','Pumpkin').replaceAll('Fulkopi','Cauliflower').replaceAll('Lau ','Bottle gourd ').replaceAll('Mulo','Radish');}else if(recipe.id.includes('chilla')||recipe.id.includes('cheela')||recipe.id.includes('besan'))recipe.cuisine='North Indian';}
function globalRecipe(recipe:Recipe,cuisine:string){recipe.cuisine=cuisine;recipes.push(recipe);}
globalRecipe(base('french-toast','Savoury French toast & tomatoes','breakfast',25,[i('Wholegrain bread',12,'slices','Grains & pulses'),i('Eggs',6,'pcs','Dairy & eggs'),i('Milk',200,'ml','Dairy & eggs'),i('Tomato',450),oil(15),salt(.5),spice('Black pepper',.25)],['Whisk eggs, milk, pepper and measured salt. Dip each slice of bread briefly in the mixture.','Cook in a nonstick pan with the measured oil until golden on both sides and the egg is fully set.','Pan-cook tomato slices until soft and serve alongside. Cut toast into manageable pieces for children.'],'A savoury preparation with no sugar or syrup. Check bread labels for salt and added sugar.','veg',['Wheat','Egg','Milk']),'French-inspired');
globalRecipe(base('frittata','Spinach & tomato pan frittata','breakfast',30,[i('Eggs',8,'pcs','Dairy & eggs'),i('Spinach',300),i('Tomato',300),i('Wholegrain bread',8,'slices','Grains & pulses'),onion(),oil(15),salt(),spice('Black pepper',.25)],['Soften onion and tomato in measured oil. Add spinach and cook until wilted.','Whisk eggs with measured salt and pepper. Pour into the pan, cover and cook on low until fully set throughout, around 12–15 minutes.','Cut into wedges and serve with toast. No oven required.'],'Cook eggs completely; keep the centre firm.','veg',['Egg','Wheat']),'Italian-inspired');
globalRecipe(base('english-eggs','Eggs, mushrooms & wholegrain toast','breakfast',25,[i('Eggs',6,'pcs','Dairy & eggs'),i('Mushrooms',450),i('Tomato',450),i('Wholegrain bread',12,'slices','Grains & pulses'),oil(15),salt(.5),spice('Black pepper',.25)],['Slice mushrooms and tomatoes; cook in half the measured oil until tender.','Scramble eggs in the remaining oil until fully set. Add the measured salt and pepper across the eggs and vegetables.','Toast bread on a tawa and serve with eggs and vegetables.'],'Use unsweetened wholegrain bread; check the label.','veg',['Egg','Wheat']),'English-inspired');
globalRecipe(base('tofu-scramble','Tofu scramble on toast','breakfast',25,[i('Tofu',600,'g','Dairy & eggs'),i('Wholegrain bread',12,'slices','Grains & pulses'),i('Tomato',300),i('Spinach',250),oil(15),salt(),spice('Turmeric')],['Crumble tofu. Cook chopped tomato and spinach in measured oil until tender.','Add tofu, turmeric and measured salt. Cook for 8–10 minutes until hot throughout.','Serve on tawa-toasted wholegrain bread.'],'Choose plain firm tofu and check bread labels.','veg',['Soy','Wheat']),'International');
globalRecipe(base('ratatouille','Pan ratatouille with white beans','curry',40,[i('Aubergine',300),i('Courgette',300),i('Capsicum',250),i('Tomato',450),lentil('Cooked white beans, unsalted',500),onion(),garlic(),oil(15),salt(),spice('Dried mixed herbs',1)],['Cut vegetables into small cubes. Soften onion and garlic in measured oil.','Add aubergine and capsicum; cook 8 minutes. Add courgette, tomatoes, herbs and 150 ml water.','Cover and simmer until tender. Add fully cooked white beans and measured salt; simmer another 8 minutes. Mash beans for young children.'],'A French-inspired vegetable and bean stew, easy to eat with rice or roti.'),'French-inspired');
globalRecipe(base('italian-chicken','Tomato & herb chicken','curry',40,[i('Skinless boneless chicken',900,'g','Fish & meat'),i('Tomato',600),i('Mushrooms',300),onion(),garlic(),oil(15),salt(),spice('Dried mixed herbs',1)],['Soften onion and garlic in measured oil. Add chopped tomatoes and herbs; simmer for 8 minutes.','Add chicken, sliced mushrooms and 250 ml water. Cover and simmer 25 minutes.','Add measured salt and check chicken reaches 74°C. Shred for children.'],chickenNote,'chicken'),'Italian-inspired');
globalRecipe(base('lemon-chicken','Lemon & herb chicken stew','curry',45,[i('Skinless boneless chicken',900,'g','Fish & meat'),i('Carrot',350),i('Green beans',300),i('Lemon',1,'pcs'),onion(),garlic(),oil(15),salt(),spice('Dried mixed herbs',1)],['Soften onion and garlic in measured oil. Add chicken, sliced carrot, herbs and 500 ml water.','Simmer covered for 25 minutes, add beans and cook until tender and chicken reaches 74°C.','Add measured salt and lemon juice. Shred the chicken for young children.'],chickenNote,'chicken'),'English-inspired');
globalRecipe(base('ginger-tofu','Ginger tofu & vegetable stir-fry','curry',30,[i('Tofu',550,'g','Dairy & eggs'),i('Green beans',350),i('Capsicum',300),ginger(),garlic(),oil(15),salt(),spice('Black pepper',.25)],['Cut tofu and vegetables into bite-sized pieces. Warm measured oil and cook ginger and garlic briefly.','Add beans and 100 ml water. Cover until nearly tender; add capsicum and tofu.','Cook until hot and tender. Season with measured salt and pepper; serve with rice. No bottled salty sauces needed.'],vegNote,'veg',['Soy']),'Asian-inspired');
globalRecipe(base('chole','Punjabi chole','curry',35,[lentil('Cooked chickpeas, unsalted',800),onion(),i('Tomato',400),ginger(),garlic(),oil(15),salt(),spice('Cumin seeds'),spice('Coriander powder',1),spice('Garam masala',.5)],['Warm oil and cumin. Soften onion, ginger and garlic, then add tomato and ground spices.','Add fully cooked chickpeas and 350 ml water. Simmer for 20 minutes.','Mash a few chickpeas to thicken the gravy. Add measured salt; mash children’s servings well.'],'Use unsalted canned chickpeas, rinsed, or chickpeas cooked until soft. No overnight soaking needed if using canned.'),'Punjabi');
globalRecipe(base('coconut-veg','Kerala-style vegetable stew','curry',35,[i('Carrot',350),i('Green beans',350),i('Cauliflower',400),lentil('Cooked chickpeas, unsalted',400),i('Light coconut milk',250,'ml','Pantry'),ginger(),oil(),salt(),spice('Black pepper',.25)],['Warm oil and sliced ginger. Add vegetables and 350 ml water; simmer covered until tender.','Add fully cooked chickpeas and light coconut milk. Simmer gently for 8 minutes, without a hard boil.','Add measured salt and pepper. Mash chickpeas for the youngest child.'],'Use light coconut milk with no added sugar. Contains coconut.'),'South Indian');
globalRecipe(base('sambar','Vegetable sambar','dal',45,[lentil('Toor dal',240),i('Carrot',200),i('Aubergine',200),i('Pumpkin',200),tomato(),oil(),salt(),spice('Mustard seeds'),spice('Coriander powder',1),spice('Turmeric'),i('Tamarind pulp, unsalted',15,'g','Pantry')],['Cook rinsed toor dal in 1.2 litres water until soft.','Add chopped vegetables, tomato, tamarind and ground spices. Simmer until tender.','Temper mustard in measured oil, stir into the dal and add measured salt.'],'Use unsalted tamarind pulp with no added sugar.','veg',['Mustard']),'South Indian');
globalRecipe(base('rasam-dal','Tomato pepper dal rasam','dal',40,[lentil('Toor dal',240),i('Tomato',450),garlic(),oil(),salt(),spice('Cumin seeds'),spice('Black pepper',.25),spice('Turmeric')],['Simmer washed dal in 1.4 litres water until very soft.','Add chopped tomatoes, crushed garlic, turmeric and pepper. Simmer for 12 minutes.','Temper cumin in measured oil and stir in. Add measured salt. Serve as a thin dal.'],'Keep pepper gentle for children.'),'South Indian');
globalRecipe(base('italian-lentils','Tomato & herb lentil stew','dal',40,[lentil('Red masoor dal',240),i('Tomato',400),i('Carrot',300),onion(),garlic(),oil(),salt(),spice('Dried mixed herbs',1)],['Soften onion, carrot and garlic in measured oil.','Add rinsed lentils, tomatoes, herbs and 1.2 litres water. Simmer 25–30 minutes until soft.','Add measured salt and water as needed for a spoonable stew.'],'An Italian-inspired lentil bowl that fills the dal place on your plate.'),'Italian-inspired');
globalRecipe(base('french-lentils','Carrot & thyme lentils','dal',45,[lentil('Whole brown lentils',240),i('Carrot',450),onion(),garlic(),oil(),salt(),spice('Dried thyme',1)],['Rinse lentils. Soften onion, garlic and finely diced carrot in measured oil.','Add lentils, thyme and 1.3 litres water. Simmer for 35–40 minutes until lentils are soft; add water as needed.','Add measured salt and lightly mash the youngest child’s serving.'],'Dried mixed herbs can replace thyme.'),'French-inspired');
for(const [id,name,veg,cuisine,seasoning] of [['poriyal','Beans poriyal','Green beans','South Indian','Mustard seeds'],['carrot-herbs','Herbed pan carrots','Carrot','French-inspired','Dried thyme'],['garlic-mushrooms','Garlic mushrooms','Mushrooms','English-inspired','Black pepper'],['italian-courgette','Italian-style courgette','Courgette','Italian-inspired','Dried mixed herbs'],['gobi-jeera','Jeera gobi','Cauliflower','North Indian','Cumin seeds'],['garlic-broccoli','Garlic broccoli','Broccoli','Asian-inspired','Black pepper']]){
 const r=bhaja(id,name,veg);r.ingredients=r.ingredients.filter(i=>!['Turmeric','Cumin seeds'].includes(i.name));r.ingredients.push(spice(seasoning,.5),garlic());r.steps=['Wash and cut vegetables into bite-sized pieces. Warm the measured oil in a wide pan.',`Add finely chopped garlic and ${seasoning.toLowerCase()}, then the vegetables. Cook on medium heat, adding a splash of water to prevent sticking.`,`Cook until tender, turning often. Add measured salt. Keep children’s portions soft.`];if(seasoning==='Mustard seeds')r.allergens=['Mustard'];globalRecipe(r,cuisine);
}
export const substitutions:Record<string,string>={
 'Bottle gourd':'Use the same weight of courgette or ridge gourd. Cooking time may be shorter.',
 'Spinach':'Use amaranth leaves in the same weight; cook until soft.',
 'Green beans':'Use the same weight of carrot or cauliflower; cook until tender.',
 'Cauliflower':'Use broccoli in the same weight; start checking tenderness earlier.',
 'Pointed gourd':'Use courgette in the same weight; it cooks more quickly.',
 'Fenugreek leaves':'Use spinach in the same weight. The flavour will be milder.',
 'Paneer':'Use the same weight of firm tofu if tolerated. Tofu contains soy; paneer contains milk.',
 'Tofu':'Use the same weight of paneer if tolerated. Paneer contains milk.',
 'Fish (rui or boneless white fish)':'Use boneless rohu, bhetki or another white fish in the same weight. Cook to 63°C. For chicken, choose a chicken recipe instead.',
 'Split moong dal':'Use red masoor dal in the same dry weight. Check tenderness from 20 minutes; adjust water.',
 'Red masoor dal':'Use split moong dal in the same dry weight; allow longer cooking until soft.',
 'Cooked chickpeas, unsalted':'Use the same weight of fully cooked unsalted kidney beans; never swap in raw beans.',
 'Mustard seeds':'For a mustard allergy, choose another dish. Removing mustard changes sarson fish curry substantially.',
 'Plain unsweetened curd':'Use an unsweetened fortified soy yoghurt if tolerated; check the pack for added sugar and allergens.'
};
// Recipe-specific corrections stay with the catalogue, not the planner.
recipes.find(r=>r.id==='lebu-dal')!.ingredients.push(i('Lemon',1,'pcs'));
recipes.find(r=>r.id==='lebu-dal')!.steps.push('Finish with lemon juice after taking the pan off the heat.');
recipes.find(r=>r.id==='doi-fish')!.allergens.push('Milk');
// Additional chicken and fish styles support the household's weekly rhythm.
for(const [id,name,veg,seasoning,cuisine] of [
 ['chicken-dhaniya','Dhaniya chicken','Courgette','Coriander powder','North Indian'],['chicken-pepper','Pepper chicken curry','Capsicum','Black pepper','South Indian'],['chicken-methi','Methi chicken','Fenugreek leaves','Cumin powder','Punjabi'],['chicken-tomato','Chicken & vegetable stew','Green beans','Dried thyme','English-inspired'],['chicken-coconut','Mild coconut chicken','Carrot','Coriander powder','South Indian']]){
 const r=base(id,name,'curry',45,[i('Skinless boneless chicken',900,'g','Fish & meat'),i(veg,450),onion(),tomato(),ginger(),garlic(),oil(15),salt(),spice(seasoning,.5)],['Soften onion, ginger and garlic in the measured oil. Add chopped tomato and the listed seasoning; cook gently for 5 minutes.',`Add chicken, chopped ${veg.toLowerCase()} and 450 ml water. Simmer covered for 25–30 minutes; add water as needed.`,`Check the chicken reaches 74°C at its thickest point and the vegetables are tender. Add measured salt; cut or shred for children.`],chickenNote,'chicken');
 if(id==='chicken-coconut'){r.ingredients.push(i('Light coconut milk',200,'ml','Pantry'));r.steps.push('Stir in light coconut milk and simmer gently for 3 minutes.');}r.cuisine=cuisine;recipes.push(r);
}
for(const [id,name,veg,cuisine] of [['fish-tamarind','Tomato imli fish curry','Tomato','South Indian'],['fish-lemon','Lemon & herb fish stew','Courgette','English-inspired'],['fish-coconut','Mild coconut fish curry','Carrot','South Indian'],['fish-ginger','Ginger fish & vegetables','Green beans','Asian-inspired']]){
 const r=fish(id,name,[i(veg,450)],`Add chopped ${veg.toLowerCase()} with 450 ml water and simmer until nearly tender.`);r.cuisine=cuisine;
 if(id==='fish-tamarind'){r.ingredients.push(i('Tamarind pulp, unsalted',15,'g','Pantry'));r.steps[1]+=' Stir in the tamarind pulp.';}
 if(id==='fish-lemon'){r.ingredients.push(i('Lemon',1,'pcs'),spice('Dried mixed herbs',1));r.steps[1]+=' Add the dried herbs.';r.steps.push('Finish with lemon juice off the heat.');}
 if(id==='fish-coconut'){r.ingredients.push(i('Light coconut milk',200,'ml','Pantry'));r.steps.push('Add light coconut milk and simmer gently for 3 minutes.');}
 recipes.push(r);
}
// Display names use familiar Hindi words in English letters, not Bengali transliterations.
const displayNames:Record<string,string>={
 'lau-moong':'Lauki moong dal','masoor':'Tomato masoor dal','palong-dal':'Palak masoor dal','lebu-dal':'Nimbu moong dal','cholar':'Chana dal with vegetables','rui-jhol':'Rohu fish curry','shorshe-fish':'Sarson fish curry','doi-fish':'Dahi fish curry','tomato-fish':'Tomato dhaniya fish curry','chicken-jhol':'Light chicken curry','palong-chicken':'Palak chicken','doi-chicken':'Dahi chicken','soy':'Soya vegetable curry','mutton':'Light mutton curry','begun':'Baingan pan-fry','bhindi':'Bhindi pan-fry','beans':'Beans pan-fry','cabbage-bhaja':'Patta gobi pan-fry','fulkopi-bhaja':'Gobi pan-fry','carrot-bhaja':'Gajar jeera pan-fry','potol':'Parwal pan-fry','courgette':'Courgette pan-fry','pumpkin-bhaja':'Kaddu pan-fry','radish-bhaja':'Mooli pan-fry','bitter-gourd':'Karela pan-fry','ridge-gourd':'Turai pan-fry','mushroom-bhaja':'Mushroom pan-fry','capsicum-bhaja':'Shimla mirch pan-fry','beetroot-bhaja':'Chukandar pan-fry','broccoli-bhaja':'Broccoli pan-fry'};
const hindiIngredients:Record<string,string>={'Bottle gourd':'Lauki (bottle gourd)','Spinach':'Palak (spinach)','Fenugreek leaves':'Methi leaves','Aubergine':'Baingan (aubergine)','Okra':'Bhindi (okra)','Cauliflower':'Gobi (cauliflower)','Cabbage':'Patta gobi (cabbage)','Carrot':'Gajar (carrot)','Pumpkin':'Kaddu (pumpkin)','Radish':'Mooli (radish)','Pointed gourd':'Parwal (pointed gourd)','Ridge gourd':'Turai (ridge gourd)','Bitter gourd':'Karela (bitter gourd)','Capsicum':'Shimla mirch (capsicum)','Beetroot':'Chukandar (beetroot)','Green peas':'Matar (green peas)','Onion':'Pyaz (onion)','Tomato':'Tamatar (tomato)','Garlic':'Lahsun (garlic)','Ginger':'Adrak (ginger)','Cucumber':'Kheera (cucumber)','Fresh coriander':'Hara dhaniya (coriander)','Lemon':'Nimbu (lemon)','Fish (rui or boneless white fish)':'Rohu or boneless white fish','Thick poha (chire)':'Thick poha','Plain unsweetened curd':'Plain dahi (unsweetened curd)'};
for(const r of recipes){
 r.englishName=r.name;
 r.name=displayNames[r.id]||r.name.replaceAll('Palong','Palak').replaceAll('palong','palak').replaceAll('Kumro','Kaddu').replaceAll('kumro','kaddu').replaceAll('Fulkopi','Gobi').replaceAll('fulkopi','gobi').replaceAll('Begun','Baingan').replaceAll('begun','baingan').replaceAll('Potol','Parwal').replaceAll('Mulo','Mooli').replaceAll('Jhinge','Turai').replaceAll(' bhaja',' pan-fry').replaceAll(' pan-bhaja',' pan-fry');
 for(const ing of r.ingredients)ing.name=hindiIngredients[ing.name]||ing.name;
 // Combine duplicate ingredients within a recipe (e.g. two additions of tomato or besan).
 const merged=new Map<string,Ingredient>();for(const ing of r.ingredients){const key=ing.name+'|'+ing.unit;const old=merged.get(key);if(old)old.qty+=ing.qty;else merged.set(key,{...ing});}r.ingredients=[...merged.values()];
}
for(const [oldName,newName] of Object.entries(hindiIngredients))if(substitutions[oldName]){substitutions[newName]=substitutions[oldName];delete substitutions[oldName];}
for(const r of recipes){const names=r.ingredients.map(i=>i.name.toLowerCase()).join(' ');for(const [tag,re] of Object.entries({Milk:/paneer|curd|yoghurt|(?<!coconut )milk/,Egg:/\beggs?\b/,Wheat:/wheat|bread|dalia|semolina/,Gluten:/wheat|bread|dalia|semolina|barley/,Soy:/tofu|soya|soy /,Mustard:/mustard|sarson/,Coconut:/coconut/,Fish:/fish/})){if(re.test(names)&&!r.allergens.includes(tag))r.allergens.push(tag);}}
export const byId=Object.fromEntries(recipes.map(r=>[r.id,r])) as Record<string,Recipe>;
export type Meal='breakfast'|'lunch'|'dinner';
export type Plan={date:string; breakfast:string[]; lunch:string[]; dinner:string[]; confirmed:boolean; vegetarian:boolean;preferences?:Preferences;sharedCurry?:boolean;takeout?:Meal[];orders?:Partial<Record<Meal,string>>};
export type State={plans:Record<string,Plan>; pantry:Record<string,string[]>; settings:{phone1:string;phone2:string;allowMutton:boolean;preferences?:Preferences};revision:number};
export const emptyState=():State=>({plans:{},pantry:{},settings:{phone1:'',phone2:'',allowMutton:false,preferences:{...defaultPreferences}},revision:0});
export function indiaDate(offset=0,now=new Date()){const date=new Date(now.getTime()+offset*86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);}
export function addDay(date:string,offset:number){return new Date(Date.parse(date+'T12:00:00Z')+offset*86400000).toISOString().slice(0,10);}
export function dateLabel(date:string){return new Date(date+'T12:00:00Z').toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short',timeZone:'Asia/Kolkata'});}
const allIds=(p:Plan)=>[...p.breakfast,...p.lunch,...p.dinner];
export const cookedIds=(p:Plan)=>(['breakfast','lunch','dinner'] as Meal[]).filter(m=>!p.takeout?.includes(m)).flatMap(m=>p[m]);
export const batchCount=(p:Plan,id:string)=>cookedIds(p).filter(v=>v===id).length;
export function batchRecipe(p:Plan,r:Recipe,prefs:Preferences=p.preferences||defaultPreferences):Recipe{const count=Math.max(1,batchCount(p,r.id));const factor=count*prefs.servings/6;return {...r,ingredients:r.ingredients.map(i=>({...i,qty:Math.round(i.qty*factor*(i.name==='Cooking oil'?prefs.oilFactor:i.name==='Salt'?prefs.saltFactor:1)*100)/100})),steps:count>1?[`Make one ${count}× batch for lunch and dinner. The ingredients below are already scaled. Use a larger pot; scale recipe water ${+factor.toFixed(2)}× too and adjust to consistency. Cooking may take longer; check doneness.`,...r.steps]:[`Ingredient quantities are scaled to ${prefs.servings} family servings for one meal. Scale recipe water ${+(prefs.servings/6).toFixed(2)}× too; adjust cooking time and check doneness.`,...r.steps]};}
export function proteinForDate(date:string,prefs:Preferences=defaultPreferences):Recipe['protein']{return prefs.diet==='mixed'?prefs.weeklyProteins[new Date(date+'T12:00:00Z').getUTCDay()]:'veg';}
export function allowedRecipe(r:Recipe,p:Preferences){return (r.kind==='grain'||p.cuisines.includes(r.cuisine as Preferences['cuisines'][number]))&&(p.diet==='mixed'||r.protein==='veg')&&(p.diet!=='vegetarian'||!r.allergens.includes('Egg'))&&!r.allergens.some(a=>p.allergies.includes(a as Preferences['allergies'][number]))&&!p.avoidIngredients.some(term=>r.ingredients.some(i=>i.name.toLowerCase().includes(term.toLowerCase())));}
export function recipeName(r:Recipe,p:Preferences){if(p.language==='hindi')return r.name;const words:Record<string,string>={palak:'spinach',saag:'greens',lauki:'bottle gourd',gobi:'cauliflower',baingan:'aubergine',bhindi:'okra',gajar:'carrot',kaddu:'pumpkin',mooli:'radish',karela:'bitter gourd',parwal:'pointed gourd',methi:'fenugreek',matar:'peas',sarson:'mustard',dahi:'yoghurt',dhaniya:'coriander',nimbu:'lemon',imli:'tamarind',chana:'chickpea',rajma:'kidney bean',moong:'mung',paneer:'paneer',dal:'lentils'};const text=r.name.replace(/patta gobi/gi,'cabbage').replace(/\b(palak|saag|lauki|gobi|baingan|bhindi|gajar|kaddu|mooli|karela|parwal|methi|matar|sarson|dahi|dhaniya|nimbu|imli|chana|rajma|moong|dal)\b/gi,w=>words[w.toLowerCase()]||w);return text[0].toUpperCase()+text.slice(1);}

function hash(value:string){let h=0;for(const ch of value)h=(h*31+ch.charCodeAt(0))>>>0;return h;}
function choose(kind:Recipe['kind'],date:string,state:State,used:string[],veg:boolean,saltKey:string,protein?:Recipe['protein']):string{
 const prefs=preferences(state);
 const recent=Object.values(state.plans).filter(p=>Math.abs(Date.parse(p.date)-Date.parse(date))<20*86400000);
 const muttonUsed=recent.filter(p=>Math.abs(Date.parse(p.date)-Date.parse(date))<14*86400000).some(p=>allIds(p).some(id=>byId[id].protein==='mutton'));
 // Reserve planned home recipes too, so restoring an order-in meal keeps weekly variety intact.
 const weekly=new Set(recent.filter(p=>p.date!==date&&Math.abs(Date.parse(p.date)-Date.parse(date))<prefs.repeatDays*86400000).flatMap(allIds));
 const candidates=recipes.filter(r=>r.kind===kind&&allowedRecipe(r,prefs)&&!used.includes(r.id)&&!weekly.has(r.id)&&(!veg||r.protein==='veg'&&!r.allergens.includes('Egg'))&&(!protein||r.protein===protein)&&(r.protein!=='mutton'||state.settings.allowMutton&&!muttonUsed));
 if(!candidates.length)throw new Error('No unused recipe fits all preferences. Try more cuisines, a shorter repeat window, or fewer ingredient exclusions. Your saved menu has not changed.');
 const cuisineCycle=['Punjabi','South Indian','Italian-inspired','Bengali','French-inspired','North Indian','Asian-inspired','English-inspired'];
 const activeCuisines=cuisineCycle.filter(c=>prefs.cuisines.includes(c as Preferences['cuisines'][number]));
 const target=activeCuisines[Math.floor(Date.parse(date)/86400000)%activeCuisines.length];
 const score=(r:Recipe)=>recent.reduce((n,p)=>n+(allIds(p).includes(r.id)?1000/(1+Math.abs(Date.parse(p.date)-Date.parse(date))/86400000):0),0)+(hash(date+saltKey+r.id)%100)/100+(r.cuisine===target?-40:0);
 return candidates.sort((a,b)=>score(a)-score(b))[0].id;
}
export function generatePlan(date:string,state:State,vegetarian=false):Plan{
 const prefs=preferences(state);
 const used:string[]=[];const weekday=new Date(date+'T12:00:00Z').getUTCDay();
 const pick=(kind:Recipe['kind'],protein?:Recipe['protein'])=>{const id=choose(kind,date,state,used,vegetarian,String(used.length),protein);used.push(id);return id;};
 const breakfast=[pick('breakfast')];let protein=vegetarian?'veg' as const:proteinForDate(date,prefs);
 const recentMutton=Object.values(state.plans).some(p=>Math.abs(Date.parse(p.date)-Date.parse(date))<14*86400000&&allIds(p).some(id=>byId[id].protein==='mutton'));
 if(prefs.diet==='mixed'&&!vegetarian&&weekday===0&&state.settings.allowMutton&&!recentMutton)protein='mutton';
 const curry=pick('curry',protein);
 for(const grain of [prefs.lunchStaple,prefs.dinnerStaple])if(!allowedRecipe(byId[grain],prefs))throw new Error('The selected staple conflicts with an ingredient or allergy restriction. Choose another staple.');
 const lunch=[prefs.lunchStaple,...(prefs.includeDal?[pick('dal')]:[]),curry,...(prefs.includeSide?[pick('bhaja')]:[])];
 const dinner=[prefs.dinnerStaple,...(prefs.includeDal?[pick('dal')]:[]),prefs.sharedCurry?curry:pick('curry',protein),...(prefs.includeSide?[pick('bhaja')]:[])];
 return {date,breakfast,lunch,dinner,confirmed:false,vegetarian,preferences:{...prefs},sharedCurry:prefs.sharedCurry,takeout:state.plans[date]?.takeout||[],orders:state.plans[date]?.orders||{}};
}
export function alternatives(plan:Plan,id:string,state:State):Recipe[]{
 const prefs=preferences(state);
 const original=byId[id];if(!original||original.kind==='grain')return [];
 const used=new Set(allIds(plan));
 for(const other of Object.values(state.plans))if(other.date!==plan.date&&Math.abs(Date.parse(other.date)-Date.parse(plan.date))<prefs.repeatDays*86400000)allIds(other).forEach(v=>used.add(v));
 const muttonUsed=Object.values(state.plans).filter(p=>Math.abs(Date.parse(p.date)-Date.parse(plan.date))<14*86400000).some(p=>allIds(p).some(v=>byId[v].protein==='mutton'));
 return recipes.filter(r=>r.kind===original.kind&&allowedRecipe(r,prefs)&&!used.has(r.id)&&(!plan.vegetarian||r.protein==='veg'&&!r.allergens.includes('Egg'))&&(r.kind!=='curry'||r.protein===original.protein)&&(r.protein!=='mutton'||state.settings.allowMutton&&!muttonUsed));
}
export function swapRecipe(plan:Plan,id:string,state:State,replacement?:string):Plan{
 if(plan.confirmed)throw new Error('Unlock this menu before making changes.');
 const recipe=byId[id];if(!recipe||!allIds(plan).includes(id)||recipe.kind==='grain')throw new Error('This dish cannot be swapped.');
 const options=alternatives(plan,id,state);
 if(replacement&&!options.some(r=>r.id===replacement))throw new Error('This alternative conflicts with the weekly variety or protein plan.');
 const next=replacement||options[0]?.id;if(!next)throw new Error('No unused alternative fits this week.');
 return {...plan,breakfast:plan.breakfast.map(v=>v===id?next:v),lunch:plan.lunch.map(v=>v===id?next:v),dinner:plan.dinner.map(v=>v===id?next:v)};
}
export function shopping(plan:Plan,prefs:Preferences=plan.preferences||defaultPreferences):Ingredient[]{const map=new Map<string,Ingredient>();for(const id of cookedIds(plan)){for(const ing of byId[id].ingredients){const key=ing.name+'|'+ing.unit;const item=map.get(key);if(item)item.qty=Math.round((item.qty+ing.qty)*100)/100;else map.set(key,{...ing});}}return [...map.values()].map(i=>({...i,qty:Math.round(i.qty*prefs.servings/6*(i.name==='Cooking oil'?prefs.oilFactor:i.name==='Salt'?prefs.saltFactor:1)*100)/100})).filter(i=>i.qty>0).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));}
export const ingredientKey=(i:Ingredient)=>i.name+'|'+i.unit;
export const quantity=(i:Ingredient)=>i.unit==='g'&&i.qty>=1000?`${+(i.qty/1000).toFixed(2)} kg`:`${i.qty} ${i.unit}`;
export const batchSafety='Set aside the dinner portion in shallow containers and refrigerate within 2 hours (1 hour above 32°C), at 4°C or colder. Reheat only the portion needed to 74°C, until steaming hot throughout. Do not leave the afternoon curry on the stove until dinner.';
export function cookMessage(plan:Plan,pantry:string[]=[],includeRecipes=false,prefs:Preferences=plan.preferences||defaultPreferences){
 const list=shopping(plan,prefs).filter(i=>!pantry.includes(ingredientKey(i)));
 const lines=[`COOK BRO • ${dateLabel(plan.date)}`,`Menu for ${profileLabel(prefs)} · ${prefs.servings} family servings per meal`,plan.confirmed?'Confirmed menu':'Suggested menu',''];
 for(const meal of ['breakfast','lunch','dinner'] as Meal[])lines.push(meal.toUpperCase(),...(plan.takeout?.includes(meal)?['ORDERING IN: no home cooking for this meal.']:plan[meal].map(id=>'• '+recipeName(byId[id],prefs))),'');
 const shared=plan.lunch.find(id=>byId[id].kind==='curry'&&plan.dinner.includes(id));
 if(shared&&batchCount(plan,shared)>1)lines.push(`COOK ONCE: ${byId[shared].name} for lunch AND dinner. Quantities below include both meals.`,batchSafety,'');
 lines.push('TO BUY',...(list.length?list.map(i=>`• ${i.name}: ${quantity(i)}`):['No additional ingredients needed.']), '','COOK NOTES','No added sugar. Measure oil and salt as listed; no deep frying. Keep chilli separate. Remove fish bones; cook meat and eggs thoroughly. Serve soft pieces for children and elders. Quantities are starting amounts for the family; adjust to appetite.');
 if(cookedIds(plan).includes('chilla'))lines.push('Tonight: soak moong dal for breakfast in the fridge.');
 if(includeRecipes){lines.push('','RECIPES');for(const id of [...new Set(cookedIds(plan))]){const r=batchRecipe(plan,byId[id],prefs);lines.push('',recipeName(r,prefs)+(batchCount(plan,id)>1?' (one batch for both meals)':''),`Ingredients: ${r.ingredients.map(i=>i.name+' '+quantity(i)).join(', ')}`,...r.steps.map((s,n)=>`${n+1}. ${s}`),r.note);}}
 return lines.join('\n');
}
