import {defaultPreferences,type Preferences} from './preferences';
export type OrderIdea={id:string;title:string;restaurant:string;url:string;protein:'veg'|'chicken'|'fish';items:string[];notes:string;source:string};
export const orderIdeas:OrderIdea[]=[
 {id:'grilled-chicken',title:'Grilled chicken, dal & chapatis',restaurant:'Savoury Restaurant · Sarjapur Road',url:'https://www.zomato.com/bangalore/savoury-restaurant-sarjapur-road/order',source:'https://www.zomato.com/bangalore/savoury-restaurant-sarjapur-road/order',protein:'chicken',items:['1 whole Alfaham chicken, cut into small pieces','1 large portion dal fry or dal tadka','1 large mixed vegetable curry','10–12 dry chapatis'],notes:'Confirm the restaurant’s portion sizes before ordering. Ask for mild seasoning, less salt and oil, no added sugar, and sauces separately. Debone children’s servings. Check the final price; this is not a quoted bundle.'},
 {id:'punjabi-veg',title:'Palak paneer, dal & rotis',restaurant:'Chulha Chauki Da Dhaba · Sarjapur Road',url:'https://www.zomato.com/bangalore/chulha-chauki-da-dhaba-sarjapur-road-bangalore/order',source:'https://www.chulhachaukidadhaba.com/menu/',protein:'veg',items:['2 portions palak paneer','1 large portion dal fry','1 mixed vegetable side if the budget permits','10–12 plain rotis or phulkas, without butter'],notes:'Choose the Sarjapur outlet in Zomato. Confirm large enough portions for the family. Ask for no cream, extra butter or added sugar; salt and recipe changes are requests, not guarantees.'},
 {id:'south-indian',title:'Idli, uttapam & sambar',restaurant:'Vedam · Doddakenelli, Sarjapur Road',url:'https://www.zomato.com/id/bangalore/vedam-sarjapur-road-bangalore/order',source:'https://www.zomato.com/id/bangalore/vedam-sarjapur-road-bangalore/order',protein:'veg',items:['12 plain idlis, check pieces per portion','3 mixed vegetable uttapams','At least 1 litre of sambar in total, ask about included portions','Chutneys separately; skip sweet drinks'],notes:'A starting family basket for breakfast or a light dinner. Confirm enough sambar is available before ordering. Ask for less oil and no extra ghee. Avoid sweetened chutneys; check coconut, mustard and other allergens.'},
 {id:'fish-curry',title:'Fish curry, dal & plain rice',restaurant:'Masala Mandi · Sarjapur Road',url:'https://www.zomato.com/bangalore/masala-mandi-sarjapur-road-bangalore/order',source:'https://www.zomato.com/bangalore/masala-mandi-sarjapur-road-bangalore/order',protein:'fish',items:['2 portions Amritsari fish curry, confirm fish quantity','1 large Punjabi dal tadka','2 portions plain steamed rice','1 vegetable side if it fits the budget'],notes:'This restaurant can be expensive. Use only if the final basket fits your budget; otherwise choose another suggestion. Ask for mild gravy, less salt and oil. Confirm boneless fish and check each child’s serving.'}
];
export const orderById=Object.fromEntries(orderIdeas.map(i=>[i.id,i]));
export function basketItems(id:string,servings:number){return (orderById[id]?.items||[]).map(item=>item.replace(/^(At least )?(\d+)(?:–(\d+))?/,(_,prefix='',n,end)=>prefix+(prefix?Math.round(Number(n)*servings/6*100)/100:Math.max(1,Math.ceil(Number(n)*servings/6)))+(end?'–'+Math.max(1,Math.ceil(Number(end)*servings/6)):'')));}
export function weekOrderCount(plans:Record<string,{date:string;takeout?:string[]}>,date:string){const d=new Date(date+'T12:00:00Z');const weekday=(d.getUTCDay()+6)%7;const start=new Date(d.getTime()-weekday*86400000).toISOString().slice(0,10);const end=new Date(Date.parse(start+'T12:00:00Z')+7*86400000).toISOString().slice(0,10);return Object.values(plans).filter(p=>p.date>=start&&p.date<end).reduce((n,p)=>n+(p.takeout?.length||0),0);}
export function orderText(id:string,p:Preferences=defaultPreferences){const o=orderById[id];return o?`${o.title}\n${p.postalCode==='560035'?o.restaurant:'Find a local restaurant in Zomato'}\nStarting quantities for ${p.servings} cooking servings, confirm restaurant portions:\n${basketItems(id,p.servings).map(i=>'• '+i).join('\n')}\nBudget cap: ₹${p.budget.toLocaleString('en-IN')} including all fees. Check the final total in Zomato.\n${o.notes}\n${p.postalCode==='560035'?o.url:'https://www.zomato.com/'}`:'';}
